/**
 * Era plates — GENERATED by tools/plates/make-plates.py. Do not edit by hand.
 *
 * One archival photograph per act, at the fidelity its era could manage: a one-bit halftone in
 * 1950, four fixed colours at 320 × 200 in the 1980s, and full colour at a resolution nobody
 * then could have displayed by the 2010s. The images live in src/art/plates/ and are imported
 * here so the bundler fingerprints them.
 *
 * `tones` is 0 for a plate left in colour, or the number of palette entries a dithered one was
 * reduced to — the renderer uses it to decide whether the image wants pixel-exact scaling.
 *
 * Every source is public domain or CC0, and every one is of a machine or a room rather than a
 * person — see the depiction rules in src/content/characters.ts. Credits are shown in game on
 * the act break and collected in the codex.
 */

import teletypeUrl from './plates/teletype.png';
import phosphorUrl from './plates/phosphor.png';
import cgaUrl from './plates/cga.png';
import webUrl from './plates/web.webp';
import glassUrl from './plates/glass.webp';
import ambientUrl from './plates/ambient.webp';

export interface Plate {
  /** Bundled asset URL. */
  url: string;
  w: number;
  h: number;
  /** 0 for a colour plate; 2 or 4 for one dithered against the era ramp. */
  tones: number;
  caption: string;
  year: string;
  credit: string;
  source: string;
}

/** Keyed by era id. Act VII has no plate on purpose. */
export const PLATES: Record<string, Plate> = {
  teletype: {
    url: teletypeUrl,
    w: 960,
    h: 600,
    tones: 2,
    caption: 'ENIAC, Ballistic Research Laboratory, Building 328',
    year: '1947',
    credit: 'U.S. Army photograph · public domain',
    source: 'https://commons.wikimedia.org/wiki/File:ARL_ENIAC_03.png',
  },
  phosphor: {
    url: phosphorUrl,
    w: 640,
    h: 400,
    tones: 4,
    caption: 'Control Data 6600 console, with its two round displays',
    year: '1964',
    credit: 'Photograph by Hullie · public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Control_Data_6600_mainframe.jpg',
  },
  cga: {
    url: cgaUrl,
    w: 320,
    h: 200,
    tones: 4,
    caption: 'Cray-1, Computer History Museum',
    year: '1976',
    credit: 'Photograph by Ed Toton · public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Cray-1_(1).jpg',
  },
  web: {
    url: webUrl,
    w: 1280,
    h: 800,
    tones: 0,
    caption: 'Columbia, NASA Advanced Supercomputing Facility',
    year: '2004',
    credit: 'Trower, NASA · public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Columbia_Supercomputer_-_NASA_Advanced_Supercomputing_Facility.jpg',
  },
  glass: {
    url: glassUrl,
    w: 1920,
    h: 1200,
    tones: 0,
    caption: 'Catalyst cluster, Lawrence Livermore National Laboratory',
    year: '2013',
    credit: 'U.S. Department of Energy · public domain',
    source: 'https://commons.wikimedia.org/wiki/File:The_catalyst_high_performance_computing_(HPC).jpg',
  },
  ambient: {
    url: ambientUrl,
    w: 1600,
    h: 1000,
    tones: 0,
    caption: 'A wafer-scale integrated circuit',
    year: '2024',
    credit: 'Wikideas1 · CC0',
    source: 'https://commons.wikimedia.org/wiki/File:Wafer-scale_integrated_circuit.png',
  },
};
