import type { Paradigm } from '../../engine/types';

export const COLLECTIVE: Paradigm[] = [
  {
    id: 'stigmergy',
    family: 'collective',
    name: 'Stigmergy',
    short: 'Coordination through the environment',
    earliest: 1959,
    prereqs: [],
    cost: 28,
    computeNeed: 4,
    capability: 2,
    understanding: 11,
    hype: 4,
    brittleness: 0.1,
    anchor: { year: 1959, who: 'Pierre-Paul Grassé' },
    codex:
      'Termites build cathedrals with no architect, no plan and almost no communication: each one deposits material where material already is, and the structure instructs the next worker. Grassé named the mechanism from studying insects, and it turns out to describe traffic, markets, software repositories and the way any large system organises without anyone holding the whole picture.',
    tags: ['founding'],
  },
  {
    id: 'blackboard',
    family: 'collective',
    name: 'Blackboard Architectures',
    short: 'Specialists writing on a shared surface',
    earliest: 1975,
    prereqs: ['stigmergy'],
    familyPrereqs: { symbolic: 10 },
    cost: 44,
    computeNeed: 7,
    capability: 7,
    understanding: 10,
    hype: 8,
    brittleness: 0.3,
    anchor: { year: 1975, who: 'Erman & Lesser — Hearsay-II' },
    codex:
      'Speech understanding needs acoustics, phonetics, syntax and semantics to constrain one another, and no sensible order to run them in. Hearsay-II gave each its own module and a shared workspace where partial hypotheses accumulated, with a scheduler deciding who speaks next. The first architecture that treated intelligence as a committee rather than a procedure.',
  },
  {
    id: 'multi-agent-systems',
    family: 'collective',
    name: 'Multi-Agent Systems',
    short: 'Negotiation as a computational primitive',
    earliest: 1980,
    prereqs: ['blackboard'],
    cost: 50,
    computeNeed: 8,
    capability: 8,
    understanding: 12,
    hype: 12,
    brittleness: 0.3,
    anchor: { year: 1980, who: 'Reid Smith — the Contract Net protocol' },
    codex:
      'Distribute a problem by having nodes announce tasks and bid for them, exactly as a firm subcontracts work. Once agents have their own goals, the interesting questions stop being algorithmic and become social: commitment, trust, coalition, betrayal. The field imported game theory wholesale and has never given it back.',
  },
  {
    id: 'ant-colony',
    family: 'collective',
    name: 'Ant Colony Optimisation',
    short: 'Pheromone trails that find short paths',
    earliest: 1992,
    prereqs: ['stigmergy'],
    cost: 48,
    computeNeed: 10,
    capability: 9,
    understanding: 10,
    hype: 16,
    brittleness: 0.3,
    anchor: { year: 1992, who: 'Marco Dorigo' },
    codex:
      'Ants lay pheromone as they travel and prefer stronger trails; short routes get reinforced faster because they are traversed more often, and evaporation forgets stale information. Dorigo turned that into a competitive combinatorial optimiser, and telecommunications firms put it to work on live network routing where the topology changes underneath you.',
    tags: ['commercial'],
  },
  {
    id: 'particle-swarm',
    family: 'collective',
    name: 'Particle Swarm Optimisation',
    short: 'Follow your best, and the flock’s best',
    earliest: 1995,
    prereqs: ['stigmergy'],
    cost: 40,
    computeNeed: 10,
    capability: 8,
    understanding: 8,
    hype: 14,
    brittleness: 0.35,
    anchor: { year: 1995, who: 'Kennedy & Eberhart' },
    codex:
      'A social psychologist and an engineer set out to simulate a flock and accidentally built an optimiser: each particle accelerates toward its own best-known position and the swarm’s, and the population converges without any gradient. Almost embarrassingly simple to implement, which is exactly why it spread into every engineering discipline that had a messy objective function.',
  },
  {
    id: 'market-mechanisms',
    family: 'collective',
    name: 'Computational Markets',
    short: 'Prices as a distributed algorithm',
    earliest: 1988,
    prereqs: ['multi-agent-systems'],
    cost: 56,
    computeNeed: 10,
    capability: 10,
    understanding: 14,
    hype: 12,
    brittleness: 0.35,
    anchor: { year: 1988, who: 'Miller & Drexler — agoric systems' },
    codex:
      'A price is a summary of everything the market knows, computed by the market, with no node holding the summary. Mechanism design asks the inverse question — what rules make honest behaviour the profitable choice? — and gives the collective school something the others lack: guarantees about what a system of self-interested parts will do.',
    tags: ['governance'],
  },
  {
    id: 'distributed-cognition',
    family: 'collective',
    name: 'Distributed Cognition',
    short: 'The unit of analysis is bigger than the skull',
    earliest: 1995,
    prereqs: ['multi-agent-systems'],
    cost: 46,
    computeNeed: 9,
    capability: 4,
    understanding: 16,
    hype: 6,
    brittleness: 0.1,
    anchor: { year: 1995, who: 'Edwin Hutchins — Cognition in the Wild' },
    codex:
      'Hutchins studied how a naval vessel navigates and found the computation distributed across charts, instruments, procedures and several people, none of whom performs it. If cognition routinely lives in the arrangement rather than the individual, then building a mind in a box may be the wrong shape of project entirely.',
    tags: ['theory'],
  },
  {
    id: 'swarm-robotics',
    family: 'collective',
    name: 'Swarm Robotics',
    short: 'Many cheap bodies, no leader',
    earliest: 2004,
    prereqs: ['particle-swarm', 'ant-colony'],
    familyPrereqs: { cybernetic: 16 },
    cost: 64,
    computeNeed: 13,
    capability: 11,
    understanding: 12,
    hype: 16,
    brittleness: 0.3,
    anchor: { year: 2004, who: 'the swarm robotics programme' },
    codex:
      'Robustness by redundancy: a thousand simple units where losing a hundred changes nothing, coordinating on local sensing alone. It inverts every assumption of classical robotics, which spends its effort making one expensive machine reliable. Warehouses, agriculture and mine-clearance took to it long before anything humanoid worked.',
    tags: ['commercial'],
  },
  {
    id: 'human-computation',
    family: 'collective',
    name: 'Human Computation',
    short: 'People as subroutines, at scale',
    earliest: 2004,
    prereqs: ['multi-agent-systems'],
    cost: 52,
    computeNeed: 13,
    capability: 12,
    understanding: 8,
    hype: 20,
    brittleness: 0.45,
    anchor: { year: 2004, who: 'von Ahn — games with a purpose' },
    codex:
      'Wrap a task machines cannot do in something people will do for free, and harvest the labelled data. It built the image corpora that the connectionists later trained on, digitised libraries a word at a time, and made explicit a dependency the field prefers not to discuss: a great deal of machine intelligence is compressed human piecework.',
    tags: ['labour'],
  },
  {
    id: 'federated-learning',
    family: 'collective',
    name: 'Federated Learning',
    short: 'Move the model, not the data',
    earliest: 2016,
    prereqs: ['human-computation'],
    familyPrereqs: { connectionist: 24 },
    cost: 72,
    computeNeed: 18,
    capability: 14,
    understanding: 12,
    hype: 18,
    brittleness: 0.25,
    anchor: { year: 2016, who: 'the federated averaging line of work' },
    codex:
      'Train across millions of devices without any of them surrendering their data: send down the weights, train locally, send back only the update. It is the collective school’s answer to centralisation, and the first architecture that made "who holds the corpus" a design parameter rather than a foregone conclusion.',
    tags: ['governance'],
  },
  {
    id: 'agent-collectives',
    family: 'collective',
    name: 'Machine Collectives',
    short: 'Societies of models, negotiating',
    earliest: 2025,
    prereqs: ['multi-agent-systems', 'federated-learning'],
    cost: 96,
    computeNeed: 23,
    capability: 24,
    understanding: 10,
    hype: 38,
    brittleness: 0.6,
    anchor: { year: 2025, who: 'the multi-agent turn' },
    codex:
      'Once a single system is competent enough to be worth talking to, the obvious move is to have many of them talk to each other — decomposing, criticising, negotiating, contracting. Capability rises; legibility collapses. Nobody has yet found a way to audit a decision that no single participant made.',
    tags: ['risk'],
  },
  {
    id: 'institutional-alignment',
    family: 'collective',
    name: 'Mechanism-Aligned Collectives',
    short: 'Rules under which many agents stay honest',
    earliest: 2033,
    prereqs: ['agent-collectives', 'market-mechanisms'],
    cost: 128,
    computeNeed: 26,
    capability: 20,
    understanding: 28,
    hype: 14,
    brittleness: 0.1,
    anchor: { year: 2033, who: '' },
    codex:
      'The oldest known method for making self-interested parties collectively trustworthy is not persuasion but institutional design: courts, audits, separated powers, adversarial process. Applied to machine collectives it produces systems whose good behaviour is a property of the arrangement rather than of any component — the only alignment story that does not require solving anyone’s interior.',
    tags: ['speculative', 'governance'],
  },
  {
    id: 'delegated-authority',
    family: 'collective',
    name: 'Delegated Authority',
    short: 'Agents that can grant and revoke each other powers',
    earliest: 2041,
    prereqs: ['institutional-alignment'],
    cost: 145,
    computeNeed: 24,
    capability: 30,
    understanding: 20,
    hype: 22,
    brittleness: 0.5,
    anchor: { year: 2041, who: '' },
    codex:
      'A collective becomes an institution at the moment its members can hand each other authority and take it back — a chain of delegation with revocation, attenuation and an audit trail, which is a thing lawyers have understood for eight hundred years and distributed systems have not. It makes a swarm accountable in the only sense that matters: you can find out who was permitted to do the thing that happened. It also makes the chain itself the attack surface, and the chain is now longer than any person can hold in mind.',
    tags: ['speculative', 'governance'],
  },
];
