import type { Paradigm } from '../../engine/types';

export const CONNECTIONIST: Paradigm[] = [
  {
    id: 'formal-neuron',
    family: 'connectionist',
    name: 'The Formal Neuron',
    short: 'A nerve cell as a logic gate',
    earliest: 1950,
    prereqs: [],
    cost: 20,
    computeNeed: 3,
    capability: 1,
    understanding: 6,
    hype: 6,
    brittleness: 0.2,
    anchor: { year: 1943, who: 'McCulloch & Pitts' },
    codex:
      'A neuron modelled as a threshold unit: sum the inputs, fire if the sum clears a bar. McCulloch and Pitts proved that networks of these can compute any logical proposition, which was taken — by both schools, in opposite directions — as evidence that brains and computers are the same kind of thing. Everything connectionist descends from this one-page abstraction.',
    tags: ['founding'],
  },
  {
    id: 'hebbian',
    family: 'connectionist',
    name: 'Hebbian Learning',
    short: 'Cells that fire together, wire together',
    earliest: 1950,
    prereqs: ['formal-neuron'],
    cost: 22,
    computeNeed: 3.5,
    capability: 1,
    understanding: 7,
    hype: 5,
    brittleness: 0.2,
    anchor: { year: 1949, who: 'Donald Hebb' },
    codex:
      'A learning rule with no teacher and no error signal: strengthen the connection between two units that are active at the same moment. It is local, biologically plausible, and by itself unstable — everything eventually connects to everything. Half a century of work consists of adding the missing term that keeps it in check.',
  },
  {
    id: 'perceptron',
    family: 'connectionist',
    name: 'The Perceptron',
    short: 'A machine that learns to see',
    earliest: 1957,
    prereqs: ['formal-neuron', 'hebbian'],
    cost: 30,
    computeNeed: 4.5,
    capability: 4,
    understanding: 5,
    hype: 38,
    brittleness: 0.8,
    anchor: { year: 1958, who: 'Frank Rosenblatt' },
    codex:
      'Rosenblatt’s convergence theorem is genuine and beautiful: if a linear separation of your data exists, the perceptron learning rule will find it in finite time. The Mark I was real hardware with a camera and motorised potentiometers, and it learned to classify shapes without being programmed. The trouble began with what was said about it in public, not with what it did on the bench.',
    tags: ['boom', 'hardware'],
  },
  {
    id: 'adaline',
    family: 'connectionist',
    name: 'Adaptive Linear Elements',
    short: 'Least-mean-squares, in analog hardware',
    earliest: 1960,
    prereqs: ['perceptron'],
    cost: 30,
    computeNeed: 5,
    capability: 5,
    understanding: 8,
    hype: 9,
    brittleness: 0.2,
    anchor: { year: 1960, who: 'Widrow & Hoff' },
    codex:
      'The quieter twin of the perceptron: minimise squared error by gradient descent, one sample at a time. Widrow’s students built it out of electroplated memistors and pointed it at telephone lines, where it became adaptive echo cancellation and made long-distance calls audible. Connectionism’s first unambiguous industrial win, and almost nobody filed it under AI.',
    tags: ['commercial'],
  },
  {
    id: 'backprop',
    family: 'connectionist',
    name: 'Backpropagation',
    short: 'Assign blame through the hidden layers',
    earliest: 1974,
    prereqs: ['adaline'],
    cost: 58,
    computeNeed: 11.2,
    capability: 12,
    understanding: 7,
    hype: 30,
    brittleness: 0.45,
    anchor: { year: 1986, who: 'Rumelhart, Hinton & Williams (after Werbos, 1974)' },
    codex:
      'The credit-assignment problem — which of the hidden units was responsible for the error? — answered by the chain rule, run backwards through the network. Werbos had it in his 1974 thesis and it went unnoticed; when the PDP volumes carried it to the field in 1986 the effect was seismic. Multi-layer networks stopped being a matter of faith.',
    tags: ['pivotal'],
  },
  {
    id: 'hopfield-nets',
    family: 'connectionist',
    name: 'Attractor Networks',
    short: 'Memory as a valley in an energy landscape',
    earliest: 1982,
    prereqs: ['hebbian'],
    cost: 44,
    computeNeed: 8,
    capability: 5,
    understanding: 13,
    hype: 20,
    brittleness: 0.25,
    anchor: { year: 1982, who: 'John Hopfield' },
    codex:
      'Hopfield showed a symmetric recurrent network has an energy function it always descends, so its stable states are memories and recall is just relaxation. That single move imported the whole apparatus of statistical physics into neural networks, and brought physicists into the field in numbers. Content-addressable memory, with no address.',
    tags: ['theory'],
  },
  {
    id: 'boltzmann',
    family: 'connectionist',
    name: 'Stochastic Networks',
    short: 'Let the units be noisy on purpose',
    earliest: 1985,
    prereqs: ['hopfield-nets'],
    cost: 52,
    computeNeed: 9,
    capability: 5,
    understanding: 14,
    hype: 12,
    brittleness: 0.2,
    anchor: { year: 1985, who: 'Hinton & Sejnowski — the Boltzmann machine' },
    codex:
      'Add thermal noise to an attractor network and it stops getting stuck in shallow valleys; anneal the temperature and it settles into deep ones. The learning rule is the difference between two correlations — one with the world clamped on, one with the network dreaming freely. Beautiful, principled, and agonisingly slow to train.',
  },
  {
    id: 'convnet',
    family: 'connectionist',
    name: 'Convolutional Networks',
    short: 'Build the structure of vision into the wiring',
    earliest: 1989,
    prereqs: ['backprop'],
    cost: 66,
    computeNeed: 12.6,
    capability: 14,
    understanding: 8,
    hype: 18,
    brittleness: 0.3,
    anchor: { year: 1989, who: 'Yann LeCun (after Fukushima’s Neocognitron, 1980)' },
    codex:
      'If the thing you are looking for can appear anywhere in the image, share the weights across positions. That one architectural prior — translation equivariance, local receptive fields, pooling — cut the parameter count enormously and made vision learnable on 1989 hardware. It read cheques for the American banking system throughout the 1990s while the field considered neural networks a dead end.',
    tags: ['commercial'],
  },
  {
    id: 'recurrent-memory',
    family: 'connectionist',
    name: 'Gated Recurrence',
    short: 'A network that can hold a thought',
    earliest: 1997,
    prereqs: ['backprop'],
    cost: 68,
    computeNeed: 12,
    capability: 12,
    understanding: 9,
    hype: 12,
    brittleness: 0.35,
    anchor: { year: 1997, who: 'Hochreiter & Schmidhuber — LSTM' },
    codex:
      'Gradients travelling back through many time steps either vanish or explode; Hochreiter diagnosed this precisely in 1991. The long short-term memory cell answers it with a protected internal state and multiplicative gates that decide what to keep, write and forget. For fifteen years it was how machines handled sequence, from handwriting to speech to translation.',
  },
  {
    id: 'deep-pretraining',
    family: 'connectionist',
    name: 'Deep Architectures',
    short: 'Many layers, finally trainable',
    earliest: 1989,
    prereqs: ['boltzmann', 'convnet'],
    cost: 80,
    computeNeed: 15.5,
    capability: 16,
    understanding: 6,
    hype: 26,
    brittleness: 0.4,
    anchor: { year: 2006, who: 'Hinton, Osindero & Teh' },
    codex:
      'Deep networks were believed untrainable — until unsupervised layer-by-layer pre-training gave them a sensible starting point, and the resulting depth turned out to matter enormously. Within a few years better initialisation, rectified units and sheer data made the pre-training step unnecessary, but the rebranding stuck. This is the moment "neural networks" became "deep learning".',
    tags: ['pivotal'],
  },
  {
    id: 'gpu-scale',
    family: 'connectionist',
    name: 'Accelerated Training at Scale',
    short: 'Large labelled data meets parallel silicon',
    earliest: 2011,
    prereqs: ['deep-pretraining'],
    familyPrereqs: { substrate: 30 },
    cost: 88,
    computeNeed: 17,
    capability: 26,
    understanding: 4,
    hype: 48,
    brittleness: 0.5,
    anchor: { year: 2012, who: 'Krizhevsky, Sutskever & Hinton — ImageNet' },
    codex:
      'The ingredients had been on the table for twenty years: convolutional nets, backpropagation, gradient descent. What was missing was a million labelled images and a pair of gaming cards. The 2012 result did not introduce an idea so much as end an argument, and the field reorganised around it within eighteen months.',
    tags: ['pivotal', 'boom'],
  },
  {
    id: 'attention',
    family: 'connectionist',
    name: 'Attention Architectures',
    short: 'Every position looks at every other',
    earliest: 2015,
    prereqs: ['recurrent-memory', 'gpu-scale'],
    cost: 96,
    computeNeed: 19,
    capability: 30,
    understanding: 6,
    hype: 42,
    brittleness: 0.45,
    anchor: { year: 2017, who: 'Vaswani et al. — the transformer' },
    codex:
      'Recurrence forces information through a sequential bottleneck. Attention replaces it with a learned, content-addressed lookup where every element can consult every other in a single parallel step — which is both a better inductive bias for language and, crucially, a shape that modern accelerators can saturate. The architecture that made scaling worth doing.',
    tags: ['pivotal'],
  },
  {
    id: 'self-supervision',
    family: 'connectionist',
    name: 'Self-Supervised Pretraining',
    short: 'The data labels itself',
    earliest: 2018,
    prereqs: ['attention'],
    /*
     * Next-token prediction trained by cross-entropy is Shannon's F_N with the estimate done by
     * gradient descent instead of by his wife guessing letters. The objective is not
     * connectionist property and never was, so the school that owns it has to have got
     * somewhere before this can.
     */
    familyPrereqs: { statistical: 36 },
    cost: 92,
    computeNeed: 20.5,
    capability: 26,
    understanding: 5,
    hype: 40,
    brittleness: 0.5,
    anchor: { year: 2018, who: 'the pretraining era' },
    codex:
      'Predicting the next token, or the masked one, needs no annotator — which removes the ceiling that labelled data had imposed on every previous method. The objective is Shannon\u2019s, exactly: minimise the cross-entropy of the next symbol given the context, the quantity he defined and measured by hand in 1951. What emerges is not a next-word predictor but whatever internal machinery next-word prediction requires, which turns out to be a great deal more than anyone expected and considerably less than the marketing claimed.',
  },
  {
    id: 'scaling-regime',
    family: 'connectionist',
    name: 'The Scaling Regime',
    short: 'Predictable returns from more of everything',
    earliest: 2020,
    prereqs: ['self-supervision'],
    cost: 120,
    computeNeed: 23,
    capability: 40,
    understanding: 3,
    hype: 60,
    brittleness: 0.6,
    anchor: { year: 2020, who: 'the empirical scaling laws' },
    codex:
      'Loss falls as a clean power law in parameters, data and compute across many orders of magnitude — which converts research into forecasting and forecasting into capital expenditure. Nothing in the curves says what capability appears at which loss, so the industry that grew around them was betting on an extrapolation whose units it could not name.',
    tags: ['boom', 'capital'],
  },
  {
    id: 'continual-networks',
    family: 'connectionist',
    name: 'Continual & Self-Modifying Networks',
    short: 'Learning that does not stop at deployment',
    earliest: 2029,
    prereqs: ['scaling-regime'],
    cost: 150,
    computeNeed: 26,
    capability: 44,
    understanding: 4,
    hype: 44,
    brittleness: 0.65,
    anchor: { year: 2029, who: '' },
    codex:
      'Every system built in the scaling regime was frozen at the moment training stopped, which made it safe in one specific sense and useless in another. Networks that keep updating on their own experience close that gap and open a worse one: the thing you audited on Tuesday is not the thing running on Friday.',
    tags: ['speculative'],
  },
];
