import type { Paradigm } from '../../engine/types';

export const CYBERNETIC: Paradigm[] = [
  {
    id: 'cybernetics',
    family: 'cybernetic',
    name: 'Cybernetics',
    short: 'Control and communication, in animal and machine',
    earliest: 1950,
    prereqs: [],
    cost: 24,
    computeNeed: 3,
    capability: 2,
    understanding: 12,
    hype: 14,
    brittleness: 0.3,
    anchor: { year: 1948, who: 'Norbert Wiener' },
    codex:
      'The first unified science of purposive behaviour: feedback, not intention, is what makes a system seek a goal, and the same mathematics covers a gun director, a thermostat and a hand reaching for a glass. It was interdisciplinary before that was a virtue, and it was displaced — not refuted — when the symbol-processing account arrived with a cleaner story and better funding.',
    tags: ['founding'],
  },
  {
    id: 'homeostasis',
    family: 'cybernetic',
    name: 'Adaptive Homeostasis',
    short: 'A machine that keeps itself stable',
    earliest: 1952,
    prereqs: ['cybernetics'],
    cost: 28,
    computeNeed: 3.5,
    capability: 3,
    understanding: 11,
    hype: 10,
    brittleness: 0.3,
    anchor: { year: 1952, who: 'W. Ross Ashby — Design for a Brain' },
    codex:
      'Ashby built a device of four coupled units that responded to any disturbance by randomly re-wiring itself until stability returned — adaptation with no model, no goal representation, no learning rule. His Law of Requisite Variety, that a controller must be at least as various as what it controls, is one of the few genuinely general theorems about intelligence anyone has.',
    tags: ['theory'],
  },
  {
    id: 'self-play-learning',
    family: 'cybernetic',
    name: 'Learning from Self-Play',
    short: 'A program that improves by playing itself',
    earliest: 1955,
    prereqs: ['cybernetics'],
    cost: 34,
    computeNeed: 5,
    capability: 6,
    understanding: 8,
    hype: 22,
    brittleness: 0.4,
    anchor: { year: 1959, who: 'Arthur Samuel — checkers' },
    codex:
      'Samuel’s checkers player tuned its own evaluation function from the outcomes of games it played against itself, and beat its author. It contains, in 1959, rote learning, a learned value function, and bootstrapping from later estimates to earlier ones — the whole skeleton of temporal-difference learning, thirty years early, in a program that fitted in a few thousand words of memory.',
    tags: ['pivotal'],
  },
  {
    id: 'optimal-control',
    family: 'cybernetic',
    name: 'Optimal Control & Filtering',
    short: 'Best estimate, best action, under noise',
    earliest: 1960,
    prereqs: ['cybernetics'],
    cost: 40,
    computeNeed: 6,
    capability: 9,
    understanding: 15,
    hype: 8,
    brittleness: 0.05,
    anchor: { year: 1960, who: 'Rudolf Kálmán; Bellman, 1957' },
    codex:
      'Dynamic programming and the Kalman filter gave engineering exact answers to estimation and control under uncertainty, and flew them to the Moon. The AI laboratories largely ignored this literature for thirty years because it was not about symbols; reinforcement learning is in large part the story of the two traditions discovering they had been writing the same equations.',
    tags: ['durable'],
  },
  {
    id: 'temporal-difference',
    family: 'cybernetic',
    name: 'Temporal Difference Learning',
    short: 'Learn from the gap between two guesses',
    earliest: 1984,
    prereqs: ['self-play-learning', 'optimal-control'],
    cost: 56,
    computeNeed: 9,
    capability: 11,
    understanding: 16,
    hype: 12,
    brittleness: 0.15,
    anchor: { year: 1988, who: 'Richard Sutton' },
    codex:
      'You do not have to wait for the final outcome to learn: the discrepancy between what you predicted a moment ago and what you predict now is itself a usable error signal. It is more efficient than waiting, it works online, and — discovered a decade later — it is approximately what dopamine neurons in the midbrain are computing.',
    tags: ['pivotal', 'theory'],
  },
  {
    id: 'q-learning',
    family: 'cybernetic',
    name: 'Model-Free Value Learning',
    short: 'Optimal action without knowing the world',
    earliest: 1989,
    prereqs: ['temporal-difference'],
    cost: 52,
    computeNeed: 10,
    capability: 12,
    understanding: 14,
    hype: 14,
    brittleness: 0.2,
    anchor: { year: 1989, who: 'Chris Watkins — Q-learning' },
    codex:
      'Watkins proved that an agent can converge on the optimal policy while acting sub-optimally and without ever building a model of its environment. That an agent can learn what is best to do without learning how the world works is one of the strangest and most consequential results in the field.',
  },
  {
    id: 'subsumption',
    family: 'cybernetic',
    name: 'Subsumption Architecture',
    short: 'Intelligence without representation',
    earliest: 1986,
    prereqs: ['homeostasis'],
    cost: 46,
    computeNeed: 7,
    capability: 8,
    understanding: 12,
    hype: 24,
    brittleness: 0.45,
    anchor: { year: 1986, who: 'Rodney Brooks' },
    codex:
      'Brooks’s robots had no world model, no planner and no central representation — just layers of tight sensor-to-actuator behaviours, with higher layers suppressing lower ones. They walked over rubble that defeated machines a thousand times more deliberate. His claim was blunt: the world is its own best model, and evolution spent its time on locomotion, not chess.',
    tags: ['pivotal'],
  },
  {
    id: 'behaviour-robotics',
    family: 'cybernetic',
    name: 'Situated Robotics',
    short: 'Competence in an unstructured world',
    earliest: 1990,
    prereqs: ['subsumption'],
    cost: 58,
    computeNeed: 10,
    capability: 12,
    understanding: 12,
    hype: 20,
    brittleness: 0.4,
    anchor: { year: 1990, who: 'the nouvelle AI programme' },
    codex:
      'Once robots had to survive corridors rather than blocks-worlds, the ranking of hard problems inverted. Moravec’s paradox, stated plainly: a machine can beat a grandmaster more easily than it can pick up his coffee cup. Everything the symbolic school considered trivial turned out to be where the difficulty lives.',
  },
  {
    id: 'developmental-robotics',
    family: 'cybernetic',
    name: 'Developmental Robotics',
    short: 'Start as an infant; grow the competence',
    earliest: 2001,
    prereqs: ['behaviour-robotics'],
    cost: 68,
    computeNeed: 13,
    capability: 10,
    understanding: 18,
    hype: 12,
    brittleness: 0.3,
    anchor: { year: 2001, who: 'the epigenetic robotics programme' },
    codex:
      'No animal is deployed fully trained. A developmental system starts with reflexes and intrinsic motivation — curiosity as a formal reward for learnable novelty — and bootstraps its own curriculum through a body that is also changing. It is the slowest route to competence anyone has proposed, and the only one with an existence proof.',
  },
  {
    id: 'predictive-coding',
    family: 'cybernetic',
    name: 'Predictive Coding',
    short: 'Perception as prediction error',
    earliest: 1999,
    prereqs: ['optimal-control'],
    familyPrereqs: { statistical: 30 },
    cost: 64,
    computeNeed: 12,
    capability: 9,
    understanding: 20,
    hype: 14,
    brittleness: 0.2,
    anchor: { year: 1999, who: 'Rao & Ballard' },
    codex:
      'The brain is not receiving the world, it is predicting the world and transmitting only its errors upward — which explains the vast descending connections that a feedforward account leaves unaccounted for. Perception becomes controlled hallucination, corrected by data. It also happens to be an extremely efficient code.',
    tags: ['theory'],
  },
  {
    id: 'deep-rl',
    family: 'cybernetic',
    name: 'Deep Reinforcement Learning',
    short: 'Value functions with learned perception',
    earliest: 2013,
    prereqs: ['q-learning'],
    familyPrereqs: { connectionist: 55 },
    cost: 84,
    computeNeed: 18,
    capability: 22,
    understanding: 8,
    hype: 44,
    brittleness: 0.55,
    anchor: { year: 2015, who: 'the Atari and Go results' },
    codex:
      'Reinforcement learning had always been limited to problems whose state you could enumerate; deep networks removed that ceiling by learning the representation and the policy together. Games fell in sequence, spectacularly and on camera. Sample efficiency remained catastrophic, and the same machine that mastered Go could not be trusted to cross a road.',
    tags: ['boom'],
  },
  {
    id: 'active-inference',
    family: 'cybernetic',
    name: 'Active Inference',
    short: 'One principle for perception and action',
    earliest: 2010,
    prereqs: ['predictive-coding'],
    cost: 86,
    computeNeed: 16,
    capability: 12,
    understanding: 26,
    hype: 14,
    brittleness: 0.25,
    anchor: { year: 2010, who: 'Karl Friston — the free energy principle' },
    codex:
      'If perception minimises prediction error by changing the model, action minimises it by changing the world — one quantity, two ways to reduce it, and no separate reward function anywhere. It is either the deepest available account of what any self-maintaining system is doing, or an unfalsifiable restatement of thermodynamics, depending entirely on who is at the whiteboard.',
    tags: ['theory'],
  },
  {
    id: 'embodied-general',
    family: 'cybernetic',
    name: 'Embodied General Competence',
    short: 'Machines that learn by living in the world',
    earliest: 2030,
    prereqs: ['developmental-robotics', 'active-inference', 'deep-rl'],
    cost: 140,
    computeNeed: 26,
    capability: 38,
    understanding: 22,
    hype: 34,
    brittleness: 0.4,
    anchor: { year: 2030, who: '' },
    codex:
      'The synthesis the cybernetic school waited eighty years for: continuous learning, in a body, under real consequences, without a training set. It is the first architecture whose failures are physical rather than textual, and the first whose competence cannot be evaluated by reading its outputs.',
    tags: ['speculative'],
  },
];
