import type { Paradigm } from '../../engine/types';

export const EVOLUTIONARY: Paradigm[] = [
  {
    id: 'self-reproducing-automata',
    family: 'evolutionary',
    name: 'Self-Reproducing Automata',
    short: 'A machine that can build itself',
    earliest: 1951,
    prereqs: [],
    cost: 26,
    computeNeed: 4,
    capability: 1,
    understanding: 12,
    hype: 8,
    brittleness: 0.15,
    anchor: { year: 1951, who: 'John von Neumann' },
    codex:
      'Von Neumann asked what a machine must contain in order to make a copy of itself, and answered it before the structure of DNA was known: a universal constructor, a tape describing it, and a copier for the tape. The logical architecture of reproduction, derived on paper. Artificial life begins here rather than with any biologist.',
    tags: ['founding', 'theory'],
  },
  {
    id: 'evolution-strategies',
    family: 'evolutionary',
    name: 'Evolution Strategies',
    short: 'Mutate the design, keep what flies',
    earliest: 1965,
    prereqs: [],
    cost: 34,
    computeNeed: 6,
    capability: 6,
    understanding: 6,
    hype: 6,
    brittleness: 0.2,
    anchor: { year: 1965, who: 'Rechenberg & Schwefel, Technische Universität Berlin' },
    codex:
      'Born in a wind tunnel, not a computer laboratory: engineers optimising the shape of a jointed plate by perturbing it at random and keeping improvements. The distinctive contribution is self-adaptation — the mutation step size is itself under selection, so the search learns how boldly to search. Unfashionable for decades, then abruptly relevant again when gradients became unavailable.',
  },
  {
    id: 'genetic-algorithms',
    family: 'evolutionary',
    name: 'Genetic Algorithms',
    short: 'Populations, crossover, selection',
    earliest: 1971,
    prereqs: ['self-reproducing-automata'],
    cost: 44,
    computeNeed: 7.5,
    capability: 8,
    understanding: 9,
    hype: 22,
    brittleness: 0.45,
    anchor: { year: 1975, who: 'John Holland — Adaptation in Natural and Artificial Systems' },
    codex:
      'Holland’s insight was that crossover is not a detail but the engine: a population implicitly evaluates an enormous number of overlapping partial solutions in parallel, and recombination assembles the good ones. It made evolution a general-purpose search method rather than a biological metaphor. Whether the schema argument actually explains its successes is disputed to this day.',
  },
  {
    id: 'classifier-systems',
    family: 'evolutionary',
    name: 'Learning Classifier Systems',
    short: 'Rules that compete for the right to act',
    earliest: 1978,
    prereqs: ['genetic-algorithms'],
    cost: 50,
    computeNeed: 8.5,
    capability: 7,
    understanding: 11,
    hype: 8,
    brittleness: 0.3,
    anchor: { year: 1978, who: 'John Holland & Judith Reitman' },
    codex:
      'An internal economy: rules bid for control, winners pay their suppliers, and a genetic algorithm breeds new rules from the wealthy ones. It is simultaneously an evolutionary method, a reinforcement learner and a symbolic rule base — the field’s first serious hybrid, arriving before either of the schools it bridges had won anything.',
    tags: ['hybrid'],
  },
  {
    id: 'artificial-life',
    family: 'evolutionary',
    name: 'Artificial Life',
    short: 'Complexity from local rules',
    earliest: 1970,
    prereqs: ['self-reproducing-automata'],
    cost: 40,
    computeNeed: 8,
    capability: 4,
    understanding: 13,
    hype: 20,
    brittleness: 0.5,
    anchor: { year: 1987, who: 'Christopher Langton (after Conway, 1970)' },
    codex:
      'The programme of studying life-as-it-could-be rather than life-as-it-is: cellular automata, digital organisms, flocking rules that produce convincing birds from three lines of arithmetic. It supplied the field with its most important negative result — that startlingly complex global behaviour needs no global controller and no representation whatsoever.',
  },
  {
    id: 'coevolution',
    family: 'evolutionary',
    name: 'Competitive Coevolution',
    short: 'Let the problem evolve too',
    earliest: 1990,
    prereqs: ['genetic-algorithms'],
    cost: 54,
    computeNeed: 10,
    capability: 9,
    understanding: 12,
    hype: 10,
    brittleness: 0.35,
    anchor: { year: 1990, who: 'Danny Hillis, on the Connection Machine' },
    codex:
      'Hillis evolved sorting networks against a coevolving population of hard test cases, and the arms race found a network better than the best hand-designed one. Fixed fitness functions plateau; opponents that improve as you do never let you. Every self-play system that came later is running Hillis’s trick.',
    tags: ['pivotal'],
  },
  {
    id: 'genetic-programming',
    family: 'evolutionary',
    name: 'Genetic Programming',
    short: 'Evolve the program, not the parameters',
    earliest: 1992,
    prereqs: ['genetic-algorithms', 'artificial-life'],
    cost: 64,
    computeNeed: 12,
    capability: 10,
    understanding: 11,
    hype: 24,
    brittleness: 0.5,
    anchor: { year: 1992, who: 'John Koza' },
    codex:
      'Represent candidates as expression trees and let crossover swap subtrees, and evolution starts producing runnable programs rather than tuned numbers. Koza documented cases where it rediscovered patented electronic circuits, and coined "human-competitive" for the standard. Its expense is bloat: without pressure toward brevity, evolved programs grow vast tumours of dead code.',
    tags: ['interpretable'],
  },
  {
    id: 'evolvable-hardware',
    family: 'evolutionary',
    name: 'Evolvable Hardware',
    short: 'Evolution exploiting the physics of the chip',
    earliest: 1996,
    prereqs: ['evolution-strategies', 'genetic-programming'],
    familyPrereqs: { substrate: 20 },
    cost: 58,
    computeNeed: 12,
    capability: 7,
    understanding: 14,
    hype: 14,
    brittleness: 0.4,
    anchor: { year: 1996, who: 'Adrian Thompson, University of Sussex' },
    codex:
      'Thompson evolved a tone discriminator directly onto a field-programmable gate array and got a working circuit using a hundred cells, several of which were not connected to anything yet were essential — it had recruited electromagnetic coupling in the substrate itself. Design without a designer produces solutions no designer would accept, and sometimes they are better.',
    tags: ['hardware'],
  },
  {
    id: 'neuroevolution',
    family: 'evolutionary',
    name: 'Neuroevolution',
    short: 'Evolve the architecture, not just the weights',
    earliest: 1975,
    prereqs: ['genetic-algorithms'],
    familyPrereqs: { connectionist: 25 },
    cost: 68,
    computeNeed: 14,
    capability: 12,
    understanding: 10,
    hype: 14,
    brittleness: 0.3,
    anchor: { year: 2002, who: 'Stanley & Miikkulainen — NEAT' },
    codex:
      'Gradient descent needs a differentiable objective and a fixed architecture; evolution needs neither. NEAT grew networks from minimal structure, protecting new topologies in their own niches long enough to become good. When reward is sparse or the architecture itself is the question, this is often the only method that works at all.',
    tags: ['hybrid'],
  },
  {
    id: 'quality-diversity',
    family: 'evolutionary',
    name: 'Quality-Diversity Search',
    short: 'Collect the interesting, not the optimal',
    earliest: 2011,
    prereqs: ['neuroevolution'],
    cost: 76,
    computeNeed: 16,
    capability: 12,
    understanding: 16,
    hype: 12,
    brittleness: 0.2,
    anchor: { year: 2015, who: 'Mouret & Clune — MAP-Elites; Lehman & Stanley — novelty search' },
    codex:
      'Lehman and Stanley found that abandoning the objective and rewarding novelty alone solved deceptive mazes that objective-driven search could not. MAP-Elites generalised it: keep the best solution in each cell of a behaviour space and you get an atlas of ways to succeed. Stepping stones to hard things rarely look like progress toward them.',
    tags: ['pivotal'],
  },
  {
    id: 'open-endedness',
    family: 'evolutionary',
    name: 'Open-Ended Systems',
    short: 'A process that never runs out of new problems',
    earliest: 2019,
    prereqs: ['quality-diversity', 'coevolution'],
    cost: 100,
    computeNeed: 20,
    capability: 18,
    understanding: 18,
    hype: 20,
    brittleness: 0.4,
    anchor: { year: 2019, who: 'the open-endedness programme' },
    codex:
      'Every optimiser eventually converges; the biosphere has not. Systems that generate their own curriculum — inventing environments as fast as they master them — are the only known way to keep a search alive indefinitely. Whether an open-ended process can be pointed at anything in particular is precisely the difficulty.',
    tags: ['speculative'],
  },
  {
    id: 'morphogenetic-systems',
    family: 'evolutionary',
    name: 'Developmental Encodings',
    short: 'Grow the design from a seed',
    earliest: 2031,
    prereqs: ['open-endedness', 'evolvable-hardware'],
    cost: 130,
    computeNeed: 24,
    capability: 24,
    understanding: 20,
    hype: 18,
    brittleness: 0.35,
    anchor: { year: 2031, who: '' },
    codex:
      'A genome does not specify an organism, it specifies a process that grows one — which is how twenty thousand genes produce a brain with a hundred trillion synapses. Encodings that develop rather than describe compress astronomically and repair themselves, and they sever the last assumption the field had kept: that a system’s structure is something a person chose.',
    tags: ['speculative'],
  },
  {
    id: 'artificial-speciation',
    family: 'evolutionary',
    name: 'Artificial Speciation',
    short: 'Populations that split rather than converge',
    earliest: 2039,
    prereqs: ['morphogenetic-systems'],
    cost: 140,
    computeNeed: 25,
    capability: 26,
    understanding: 22,
    hype: 16,
    brittleness: 0.4,
    anchor: { year: 2039, who: '' },
    codex:
      'Every optimiser this century converged, which is what optimisers are for and why none of them stayed interesting. Systems that reward divergence — that reproductively isolate sub-populations the moment they find different ways of being good — stop producing an answer and start producing a lineage. You no longer get the best solution. You get a family tree of solutions, most of them worthless, a few of them doing things nobody specified, and no way to ask for one in particular.',
    tags: ['speculative'],
  },
];
