import type { Paradigm } from '../../engine/types';

export const STATISTICAL: Paradigm[] = [
  {
    id: 'information-theory',
    family: 'statistical',
    name: 'Information Theory',
    short: 'Surprise, measured in bits',
    earliest: 1950,
    prereqs: [],
    cost: 24,
    computeNeed: 3,
    capability: 2,
    understanding: 10,
    hype: 6,
    brittleness: 0.05,
    anchor: { year: 1948, who: 'Claude Shannon' },
    codex:
      'Shannon gave "information" a unit and a limit, and in doing so handed the next century a currency for talking about learning: a model is good exactly to the extent that it makes the data unsurprising. Compression, prediction and understanding turn out to be three descriptions of one activity — a claim the field would rediscover roughly every fifteen years.',
    tags: ['founding', 'theory'],
  },
  {
    id: 'language-entropy',
    family: 'statistical',
    name: 'The Entropy of a Language',
    short: 'Score a model of English by how well it guesses the next letter',
    earliest: 1951,
    prereqs: ['information-theory'],
    cost: 28,
    computeNeed: 3.5,
    capability: 3,
    understanding: 11,
    hype: 5,
    brittleness: 0.05,
    anchor: { year: 1951, who: 'Claude Shannon — Prediction and Entropy of Printed English' },
    codex:
      'Shannon defined F_N, the entropy of the next letter given the preceding N-1, and computed it upward from letter frequencies: 4.7 bits with no model at all, 4.14 from single letters, 3.56 from digrams, 3.3 from trigrams. Then, to reach the long-range structure no table could hold, he ran the experiment on a person — a subject guessing a novel letter by letter, told only whether each guess was right — and bounded English at roughly one bit per character, about 75% redundant. The training objective of every language model since is that quantity minimised by machine instead of estimated by hand, and perplexity is only F_N in different clothing. The field spent seventy years building a better predictor for a benchmark that was already defined and already measured.',
    tags: ['founding', 'theory', 'pivotal'],
  },
  {
    id: 'statistical-pattern-recognition',
    family: 'statistical',
    name: 'Statistical Pattern Recognition',
    short: 'Decision boundaries from densities',
    earliest: 1957,
    prereqs: ['information-theory'],
    cost: 30,
    computeNeed: 5,
    capability: 5,
    understanding: 8,
    hype: 5,
    brittleness: 0.1,
    anchor: { year: 1967, who: 'Cover & Hart — nearest neighbour' },
    codex:
      'While the AI laboratories argued about symbols, the engineering departments were quietly classifying radar returns and postal codes with Bayes decision rules and nearest-neighbour lookups. Cover and Hart’s result — that plain nearest neighbour is at worst twice the optimal error rate — is the sort of guarantee the symbolic school could never offer about anything.',
  },
  {
    id: 'algorithmic-probability',
    family: 'statistical',
    name: 'Algorithmic Probability',
    short: 'The shortest program is the best explanation',
    earliest: 1964,
    prereqs: ['information-theory'],
    cost: 44,
    computeNeed: 5,
    capability: 1,
    understanding: 18,
    hype: 4,
    brittleness: 0.05,
    anchor: { year: 1964, who: 'Ray Solomonoff' },
    codex:
      'Solomonoff defined a prior over every possible computable explanation, weighted by brevity, and proved it converges on the truth faster than any other predictor. It is also uncomputable, which is why it spent decades as a philosophical curiosity rather than a method. Every practical thing anyone has ever said about Occam’s razor is a tractable approximation to this.',
    tags: ['theory', 'long-shot'],
  },
  {
    id: 'em-latent',
    family: 'statistical',
    name: 'Latent Variable Estimation',
    short: 'Fit what you cannot see',
    earliest: 1970,
    prereqs: ['statistical-pattern-recognition'],
    cost: 42,
    computeNeed: 7,
    capability: 8,
    understanding: 10,
    hype: 6,
    brittleness: 0.1,
    anchor: { year: 1977, who: 'Dempster, Laird & Rubin — EM; Baum — HMMs' },
    codex:
      'Alternate between guessing the hidden variables given your model and refitting the model given your guesses; the likelihood never decreases. Applied to hidden Markov models it gave speech recognition its first working decade, and it did so by treating language as a stochastic process — a position the linguistics establishment found close to obscene.',
    tags: ['commercial'],
  },
  {
    id: 'vc-theory',
    family: 'statistical',
    name: 'Statistical Learning Theory',
    short: 'Why generalisation is possible at all',
    earliest: 1971,
    prereqs: ['statistical-pattern-recognition'],
    cost: 50,
    computeNeed: 7,
    capability: 3,
    understanding: 20,
    hype: 5,
    brittleness: 0.05,
    anchor: { year: 1971, who: 'Vapnik & Chervonenkis' },
    codex:
      'A bound on how far test error can stray from training error, in terms of a capacity measure of the hypothesis class. It explains overfitting rigorously and prescribes the cure — control capacity, not just error. Its later embarrassment, that hugely over-parameterised networks generalise anyway, is one of the genuinely open problems the field is still carrying.',
    tags: ['theory'],
  },
  {
    id: 'bayes-nets',
    family: 'statistical',
    name: 'Bayesian Networks',
    short: 'Uncertainty with an honest structure',
    earliest: 1985,
    prereqs: ['em-latent'],
    cost: 60,
    computeNeed: 9,
    capability: 11,
    understanding: 17,
    hype: 16,
    brittleness: 0.1,
    anchor: { year: 1985, who: 'Judea Pearl' },
    codex:
      'Expert systems handled uncertainty with invented certainty factors that did not compose. Pearl showed that a directed graph of conditional independences lets you do genuine probabilistic inference at tractable cost, and that the graph itself is the domain knowledge. This is the argument that ended the ad-hoc era and it won on mathematics, not on demonstrations.',
    tags: ['pivotal', 'interpretable'],
  },
  {
    id: 'mcmc',
    family: 'statistical',
    name: 'Monte Carlo Inference',
    short: 'Sample when you cannot integrate',
    earliest: 1984,
    prereqs: ['em-latent'],
    cost: 52,
    computeNeed: 10,
    capability: 9,
    understanding: 12,
    hype: 6,
    brittleness: 0.1,
    anchor: { year: 1984, who: 'Geman & Geman; Gelfand & Smith, 1990' },
    codex:
      'Most interesting posteriors have no closed form, so build a Markov chain whose stationary distribution is the thing you want and walk it. Trading exactness for compute in this way turned Bayesian statistics from a philosophical position into a working practice, and made everything downstream of it possible.',
  },
  {
    id: 'kernel-methods',
    family: 'statistical',
    name: 'Kernel Methods',
    short: 'Linear separation in a space you never visit',
    earliest: 1992,
    prereqs: ['vc-theory'],
    cost: 64,
    computeNeed: 11,
    capability: 14,
    understanding: 15,
    hype: 24,
    brittleness: 0.25,
    anchor: { year: 1995, who: 'Cortes & Vapnik — support vector machines' },
    codex:
      'Map the data into a very high-dimensional space where it is linearly separable, then notice you only ever need inner products and skip the mapping entirely. Convex, so training has one answer and finds it; bounded, so generalisation is provable. Through the late 1990s this simply beat neural networks on most benchmarks, and it deserved to.',
    tags: ['boom'],
  },
  {
    id: 'ensembles',
    family: 'statistical',
    name: 'Ensemble Methods',
    short: 'Many weak opinions, one strong answer',
    earliest: 1995,
    prereqs: ['statistical-pattern-recognition'],
    cost: 48,
    computeNeed: 11,
    capability: 13,
    understanding: 10,
    hype: 10,
    brittleness: 0.1,
    anchor: { year: 1997, who: 'Freund & Schapire — AdaBoost; Breiman — random forests, 2001' },
    codex:
      'Schapire’s answer to a theoretical question — can a barely-better-than-chance learner be boosted to arbitrary accuracy? — was yes, and the constructive proof turned out to be an excellent algorithm. Combined with bagging and decision trees, this quietly won the practical machine-learning world for a decade and still wins on tabular data.',
    tags: ['durable', 'commercial'],
  },
  {
    id: 'causal-inference',
    family: 'statistical',
    name: 'Causal Inference',
    short: 'Doing is not the same as seeing',
    earliest: 2000,
    prereqs: ['bayes-nets'],
    cost: 74,
    computeNeed: 12,
    capability: 10,
    understanding: 24,
    hype: 12,
    brittleness: 0.1,
    anchor: { year: 2000, who: 'Judea Pearl — Causality' },
    codex:
      'A calculus that distinguishes observing a variable from intervening on it, and says precisely when a causal effect can be recovered from data you already have. It is the formal machinery for counterfactuals, and therefore for explanation, blame and responsibility — every question a purely predictive system is structurally unable to answer.',
    tags: ['interpretable', 'governance'],
  },
  {
    id: 'probabilistic-programming',
    family: 'statistical',
    name: 'Probabilistic Programming',
    short: 'A model is a program with random choices',
    earliest: 2008,
    prereqs: ['mcmc', 'bayes-nets'],
    cost: 78,
    computeNeed: 14,
    capability: 12,
    understanding: 18,
    hype: 14,
    brittleness: 0.2,
    anchor: { year: 2008, who: 'Goodman et al. — Church' },
    codex:
      'Write a generative story as ordinary code, mark the uncertain bits, and let a universal inference engine run it backwards from the observations. It makes the structure of a model legible in a way a weight matrix never is, and it inherits every hard problem in inference at once — which is why its adoption has always trailed its elegance.',
    tags: ['interpretable'],
  },
  {
    id: 'universal-agents',
    family: 'statistical',
    name: 'Universal Agent Theory',
    short: 'The optimal agent, if compute were free',
    earliest: 2000,
    prereqs: ['algorithmic-probability'],
    cost: 66,
    computeNeed: 12,
    capability: 2,
    understanding: 22,
    hype: 6,
    brittleness: 0.05,
    anchor: { year: 2000, who: 'Marcus Hutter — AIXI' },
    codex:
      'Bolt Solomonoff’s prior onto expected-reward maximisation and you have a specification of the optimal agent in any computable environment. It is spectacularly uncomputable, so it functions as a definition rather than a design — but a field arguing about what intelligence *is* benefits enormously from having one exact answer to point at, even an unbuildable one.',
    tags: ['theory'],
  },
  {
    id: 'uncertainty-at-scale',
    family: 'statistical',
    name: 'Calibrated Large Models',
    short: 'A system that knows what it does not know',
    earliest: 2027,
    prereqs: ['probabilistic-programming'],
    familyPrereqs: { connectionist: 60 },
    cost: 130,
    computeNeed: 25,
    capability: 22,
    understanding: 30,
    hype: 18,
    brittleness: 0.1,
    anchor: { year: 2027, who: '' },
    codex:
      'The oldest complaint about large learned systems is that they are equally fluent when right and when wrong. Fusing genuine posterior machinery with models at scale gives outputs that carry honest error bars — slower, more expensive, and the first version of the technology that an engineer could sign off on.',
    tags: ['speculative', 'governance'],
  },
];
