import type { Paradigm } from '../../engine/types';

/**
 * Substrate nodes are the only ones that bend the compute curve (see sim.ts). Backing this
 * family is the slowest possible way to look productive and the fastest way to change what
 * every other family is allowed to attempt.
 */
export const SUBSTRATE: Paradigm[] = [
  {
    id: 'analog-computing',
    family: 'substrate',
    name: 'Analog Computing',
    short: 'The circuit *is* the equation',
    earliest: 1950,
    prereqs: [],
    cost: 26,
    computeNeed: 2,
    capability: 4,
    understanding: 8,
    hype: 10,
    brittleness: 0.25,
    anchor: { year: 1950, who: 'the electronic differential analyser' },
    codex:
      'Represent a variable as a voltage and an integration as a capacitor, and a differential equation solves itself at the speed of electricity, in parallel, for a few watts. Analog machines flew aircraft and designed reactors while digital computers were still counting in the hundreds of operations per second. They lost on precision, repeatability and programmability — never on speed or energy.',
    tags: ['founding', 'hardware'],
  },
  {
    id: 'stored-program-scale',
    family: 'substrate',
    name: 'Stored-Program Machines',
    short: 'Instructions in the same memory as data',
    earliest: 1950,
    prereqs: [],
    cost: 24,
    computeNeed: 2,
    capability: 3,
    understanding: 6,
    hype: 8,
    brittleness: 0.1,
    anchor: { year: 1949, who: 'the first stored-program computers' },
    codex:
      'A machine that holds its own instructions in rewritable memory can modify them, which is the precondition for a program that changes itself. Everything in this game rests on that one architectural decision, and on the fact that the machines got faster every year without anybody in AI having to do anything about it.',
    dividend: 9,
    tags: ['founding'],
  },
  {
    id: 'neural-hardware',
    family: 'substrate',
    name: 'Purpose-Built Learning Hardware',
    short: 'Weights as physical quantities',
    earliest: 1958,
    prereqs: ['analog-computing'],
    familyPrereqs: { connectionist: 12 },
    cost: 34,
    computeNeed: 4,
    capability: 5,
    understanding: 7,
    hype: 20,
    brittleness: 0.5,
    anchor: { year: 1960, who: 'the Mark I Perceptron; Widrow’s memistors' },
    codex:
      'The first neural networks were not simulations — they were cabinets of motor-driven potentiometers and electrochemical cells, where a weight was a physical resistance and learning was a motor turning. Slow, drifty, and impossible to debug. They were also the last time for fifty years that learning ran natively in the substrate rather than on top of an unrelated one.',
    tags: ['hardware'],
  },
  {
    id: 'integrated-circuits',
    family: 'substrate',
    name: 'Integrated Circuits',
    short: 'The doubling that funded everything',
    earliest: 1965,
    prereqs: ['stored-program-scale'],
    cost: 40,
    computeNeed: 5,
    capability: 6,
    understanding: 5,
    hype: 12,
    brittleness: 0.1,
    anchor: { year: 1965, who: 'Gordon Moore’s observation' },
    codex:
      'Not an AI result at all, and the single most important input to the field’s history. A geometric improvement arriving reliably for half a century meant that any approach limited only by compute would eventually become feasible, and any approach limited by ideas would not. It quietly decided several arguments that the participants believed they were winning on merit.',
    dividend: 12,
    tags: ['hardware', 'durable'],
  },
  {
    id: 'vlsi',
    family: 'substrate',
    name: 'VLSI Design Methodology',
    short: 'Anyone can lay out a chip',
    earliest: 1980,
    prereqs: ['integrated-circuits'],
    cost: 46,
    computeNeed: 7,
    capability: 7,
    understanding: 8,
    hype: 8,
    brittleness: 0.1,
    anchor: { year: 1980, who: 'Mead & Conway' },
    codex:
      'Mead and Conway turned chip design from a craft guarded by a few firms into something a university course could teach, with abstractions clean enough that a graduate student could tape out a custom processor. Every subsequent piece of special-purpose hardware in this story — neuromorphic, parallel, accelerated — exists because of that democratisation.',
    dividend: 10,
    tags: ['hardware'],
  },
  {
    id: 'massively-parallel',
    family: 'substrate',
    name: 'Massively Parallel Machines',
    short: 'Sixty-five thousand small processors',
    earliest: 1985,
    prereqs: ['vlsi'],
    cost: 54,
    computeNeed: 9,
    capability: 9,
    understanding: 8,
    hype: 22,
    brittleness: 0.45,
    anchor: { year: 1985, who: 'Danny Hillis — the Connection Machine' },
    codex:
      'Hillis reasoned that if a brain is a great many slow elements, a thinking machine should be too, and built a cube of blinking lights containing sixty-five thousand one-bit processors. Its commercial failure was total and its intellectual influence enormous: data-parallel programming, and the demonstration that the bottleneck is communication rather than arithmetic.',
    dividend: 8,
    tags: ['hardware'],
  },
  {
    id: 'neuromorphic-vlsi',
    family: 'substrate',
    name: 'Neuromorphic VLSI',
    short: 'Silicon that computes like nerve tissue',
    earliest: 1989,
    prereqs: ['vlsi', 'analog-computing'],
    cost: 62,
    computeNeed: 9,
    capability: 8,
    understanding: 14,
    hype: 16,
    brittleness: 0.3,
    anchor: { year: 1989, who: 'Carver Mead — Analog VLSI and Neural Systems' },
    codex:
      'Mead noticed that transistors operated below threshold obey nearly the same exponential physics as ion channels, so a retina can be built rather than simulated. The resulting chips ran on microwatts and responded in real time. Their curse has been fabrication variation — every chip is slightly different, which is exactly how biology works and exactly what digital engineering exists to prevent.',
    tags: ['hardware'],
  },
  {
    id: 'molecular-computing',
    family: 'substrate',
    name: 'Molecular Computing',
    short: 'Computation in a test tube',
    earliest: 1961,
    prereqs: ['analog-computing'],
    cost: 58,
    computeNeed: 10,
    capability: 4,
    understanding: 14,
    hype: 18,
    brittleness: 0.55,
    anchor: { year: 1994, who: 'Leonard Adleman — DNA solution to a Hamiltonian path' },
    codex:
      'Adleman solved a seven-city path problem by letting strands of DNA anneal, encoding the graph in base pairs and reading the answer off a gel. Astronomical parallelism, appalling latency, and an error rate that grows with the problem. It is the clearest demonstration that computation is a thing matter does, not a thing computers do.',
    tags: ['hardware', 'long-shot'],
  },
  {
    id: 'reservoir-computing',
    family: 'substrate',
    name: 'Reservoir Computing',
    short: 'Train only the readout; leave the tangle alone',
    // Rosenblatt's random projection layers already contain the idea; what took forty years
    // was hardware able to run a large enough tangle to make it worth anything.
    earliest: 1962,
    prereqs: [],
    familyPrereqs: { connectionist: 30 },
    cost: 56,
    computeNeed: 12,
    capability: 9,
    understanding: 14,
    hype: 10,
    brittleness: 0.2,
    anchor: { year: 2001, who: 'Jaeger — echo state networks; Maass — liquid state machines' },
    codex:
      'A large random recurrent network already projects its input history into a rich high-dimensional space; you need only fit a linear readout on top. This makes training trivial and lets the reservoir be almost anything with complex dynamics — a photonic cavity, a bucket of water, an FPGA. Computation as a property of matter in motion.',
  },
  {
    id: 'gpu-general-compute',
    family: 'substrate',
    name: 'General-Purpose Accelerators',
    short: 'Graphics silicon, pointed at arithmetic',
    earliest: 2007,
    prereqs: ['massively-parallel'],
    cost: 66,
    computeNeed: 14,
    capability: 14,
    understanding: 4,
    hype: 24,
    brittleness: 0.2,
    anchor: { year: 2007, who: 'programmable GPU compute' },
    codex:
      'The video game industry spent two decades funding massively parallel floating-point hardware for reasons entirely unrelated to intelligence, and then someone noticed that a matrix multiply is a matrix multiply. It is the largest accidental subsidy in the history of the field, and it arrived exactly when the connectionists needed it.',
    dividend: 10,
    tags: ['hardware', 'pivotal'],
  },
  {
    id: 'memristive-compute',
    family: 'substrate',
    name: 'In-Memory Computing',
    short: 'Stop moving data to the arithmetic',
    earliest: 2008,
    prereqs: ['neuromorphic-vlsi'],
    cost: 74,
    computeNeed: 16,
    capability: 13,
    understanding: 10,
    hype: 20,
    brittleness: 0.35,
    anchor: { year: 2008, who: 'the memristor as a physical device' },
    codex:
      'Nearly all the energy in a modern accelerator is spent shuttling numbers between memory and arithmetic units. A crossbar of resistive elements performs a matrix-vector product in one step, in place, by Ohm’s law — the analog approach returning through the back door, now with the precision problem reframed as an acceptable noise floor.',
    tags: ['hardware'],
  },
  {
    id: 'spiking-hardware',
    family: 'substrate',
    name: 'Spiking Neuromorphic Systems',
    short: 'Events, not clock cycles',
    earliest: 2012,
    prereqs: ['neuromorphic-vlsi'],
    cost: 78,
    computeNeed: 17,
    capability: 12,
    understanding: 14,
    hype: 18,
    brittleness: 0.3,
    anchor: { year: 2014, who: 'the large-scale spiking processors' },
    codex:
      'A brain runs on twenty watts because nothing happens until something changes. Spiking hardware is asynchronous and event-driven, with computation and communication in the same currency, and gets orders of magnitude better energy per operation. The obstacle has never been the chips; it is that nobody knows how to train them nearly as well as backpropagation trains the alternative.',
    tags: ['hardware'],
  },
  {
    id: 'photonic-compute',
    family: 'substrate',
    name: 'Photonic Computing',
    short: 'Matrix multiplication at the speed of light',
    earliest: 2017,
    prereqs: ['memristive-compute'],
    cost: 88,
    computeNeed: 20,
    capability: 16,
    understanding: 10,
    hype: 22,
    brittleness: 0.4,
    anchor: { year: 2017, who: 'integrated optical neural networks' },
    codex:
      'Interference performs linear algebra for free: send light through a mesh of interferometers and the transformation happens in transit, with no clock and almost no heat. What it cannot do is the nonlinearity, or hold a value, so every photonic system is a hybrid — and the conversions at each boundary are where the savings go to die.',
    tags: ['hardware'],
  },
  {
    id: 'quantum-ml',
    family: 'substrate',
    name: 'Quantum Machine Learning',
    short: 'Amplitudes as a feature space',
    earliest: 1985,
    prereqs: ['molecular-computing'],
    cost: 96,
    computeNeed: 20,
    capability: 8,
    understanding: 18,
    hype: 34,
    brittleness: 0.75,
    anchor: { year: 2014, who: 'the variational quantum algorithms' },
    codex:
      'A quantum state is a vector in an exponentially large space, which sounds exactly like the feature space a kernel method wants — until you account for the cost of getting classical data in and classical answers out. It has attracted funding out of all proportion to its demonstrated results, which makes it the purest example in the game of hype outrunning delivery.',
    tags: ['hardware', 'hype-risk'],
  },
  {
    id: 'thermodynamic-compute',
    family: 'substrate',
    name: 'Thermodynamic Computing',
    short: 'Let noise do the sampling',
    earliest: 2029,
    prereqs: ['memristive-compute', 'photonic-compute'],
    cost: 120,
    computeNeed: 25,
    capability: 26,
    understanding: 16,
    hype: 20,
    brittleness: 0.3,
    anchor: { year: 2029, who: '' },
    codex:
      'Digital hardware spends most of its energy suppressing thermal noise; a sampler wants that noise and has to synthesise it at enormous cost. Hardware that treats fluctuation as the computational resource rather than the enemy inverts the entire energy budget of probabilistic inference — and makes Bayesian methods cheap for the first time since anyone proposed them.',
    tags: ['speculative', 'hardware'],
  },
  {
    id: 'reversible-compute',
    family: 'substrate',
    name: 'Reversible Computing',
    short: 'Computation that does not throw heat away',
    earliest: 2041,
    prereqs: ['thermodynamic-compute'],
    cost: 140,
    computeNeed: 26,
    capability: 30,
    understanding: 18,
    hype: 18,
    brittleness: 0.35,
    dividend: 14,
    anchor: { year: 2041, who: '' },
    codex:
      'Landauer showed in 1961 that erasing a bit has a thermodynamic price and that computation which never erases has none. For eighty years that was a curiosity, because the price was negligible beside everything else wasted. Once the frontier is limited by what can be cooled rather than what can be fabricated, it stops being a curiosity and becomes the only remaining direction — and a machine that must not forget anything in order to run at all is a strange thing to build a mind on.',
    tags: ['speculative', 'hardware'],
  },
];
