import type { Paradigm } from '../../engine/types';

/*
 * This school's hype was under-priced for a long time, which flattered it. It is the one that
 * promised a chess champion within ten years in 1958, a machine that would read Shakespeare and
 * do everything a mind does, a national programme of inference engines, and a knowledge base
 * that would contain common sense. Those were not modest claims and they were not met, and the
 * five nodes that made them now carry the expectation they actually generated.
 *
 * Which is separate from the school being right about a great deal — see the four nodes from
 * 2001 onward, whose hype is deliberately near zero because nobody promised anything about them
 * and they simply worked.
 */
export const SYMBOLIC: Paradigm[] = [
  {
    id: 'logic-theorist',
    family: 'symbolic',
    name: 'Heuristic Proof Search',
    short: 'A machine that proves theorems',
    earliest: 1955,
    prereqs: [],
    cost: 24,
    computeNeed: 4.5,
    capability: 2,
    understanding: 4,
    hype: 8,
    brittleness: 0.3,
    anchor: { year: 1956, who: 'Newell, Simon & Shaw — Logic Theorist' },
    codex:
      'The first program that did something everyone agreed was thinking: it proved theorems from Principia Mathematica, and found a proof of one that was shorter than Russell and Whitehead’s. Its real contribution was the idea of heuristic search — you cannot examine every branch, so you use rules of thumb to decide which branch is worth examining. Nearly all of symbolic AI is a variation on that sentence.',
    tags: ['founding'],
  },
  {
    id: 'lisp',
    family: 'symbolic',
    name: 'List Processing',
    short: 'A language where code is data',
    earliest: 1958,
    prereqs: ['logic-theorist'],
    cost: 28,
    computeNeed: 5,
    capability: 3,
    understanding: 6,
    hype: 4,
    brittleness: 0.1,
    anchor: { year: 1958, who: 'John McCarthy' },
    codex:
      'McCarthy wanted a notation for writing programs that reason about programs, and produced a language in which the two are the same kind of object. Recursion, garbage collection, the read-eval-print loop and the conditional expression all arrive together. For thirty years, if you were doing AI, you were almost certainly doing it in some dialect of this.',
    tags: ['tooling'],
  },
  {
    id: 'gps',
    family: 'symbolic',
    name: 'Means-Ends Analysis',
    short: 'Close the gap between here and the goal',
    earliest: 1959,
    prereqs: ['logic-theorist'],
    cost: 32,
    computeNeed: 5.2,
    capability: 3,
    understanding: 5,
    hype: 26,
    brittleness: 0.7,
    anchor: { year: 1959, who: 'Newell & Simon — General Problem Solver' },
    codex:
      'Measure the difference between the current state and the goal, find an operator that reduces that difference, apply it, repeat. Its authors believed it modelled how people actually solve problems, and collected think-aloud protocols to check. The word "General" in the name turned out to be the expensive part: it was general over toy problems and helpless outside them.',
  },
  {
    id: 'heuristic-search',
    family: 'symbolic',
    name: 'Informed Search',
    short: 'Admissible heuristics, optimal paths',
    earliest: 1966,
    prereqs: ['gps'],
    cost: 34,
    computeNeed: 6,
    capability: 5,
    understanding: 7,
    hype: 3,
    brittleness: 0.05,
    anchor: { year: 1968, who: 'Hart, Nilsson & Raphael — A*' },
    codex:
      'The proof that if your heuristic never overestimates the remaining distance, best-first search finds the optimal path and expands no more nodes than necessary. Unglamorous, entirely correct, and still running inside every route planner and game engine on Earth. Symbolic AI’s most durable export.',
    tags: ['durable'],
  },
  {
    id: 'resolution',
    family: 'symbolic',
    name: 'Resolution Theorem Proving',
    short: 'One inference rule, mechanically complete',
    earliest: 1965,
    prereqs: ['lisp'],
    cost: 36,
    computeNeed: 6,
    capability: 3,
    understanding: 9,
    hype: 6,
    brittleness: 0.2,
    anchor: { year: 1965, who: 'J. Alan Robinson' },
    codex:
      'Robinson reduced first-order logical inference to a single rule applied to clauses, with unification doing the pattern matching. Complete, in the sense that anything entailed will eventually be derived — where "eventually" is doing an enormous amount of work. The gap between completeness and tractability is the central tragedy of the logical approach.',
  },
  {
    id: 'logic-programming',
    family: 'symbolic',
    name: 'Logic Programming',
    short: 'State the problem; the prover is the program',
    earliest: 1972,
    prereqs: ['resolution'],
    cost: 42,
    computeNeed: 6.8,
    capability: 6,
    understanding: 8,
    hype: 20,
    brittleness: 0.55,
    anchor: { year: 1972, who: 'Colmerauer & Kowalski — Prolog' },
    codex:
      'If resolution can derive anything entailed by your axioms, then writing the axioms *is* programming. Prolog made that practical by fixing a search order, which meant the declarative dream came with a very procedural set of things you had to know about clause ordering. Europe and later Japan bet heavily on it.',
  },
  {
    id: 'expert-systems',
    family: 'symbolic',
    name: 'Expert Systems',
    short: 'Bottle a specialist in a thousand rules',
    earliest: 1968,
    prereqs: ['lisp'],
    cost: 46,
    computeNeed: 6.5,
    capability: 9,
    understanding: 4,
    hype: 40,
    brittleness: 0.85,
    anchor: { year: 1972, who: 'Feigenbaum, Buchanan & Shortliffe — DENDRAL, MYCIN' },
    codex:
      'The strategic retreat that worked: stop trying to build general intelligence, interview a domain expert, and encode their rules. MYCIN diagnosed blood infections about as well as the faculty. The catch is that such a system has no idea where its own edges are — one step outside its rules it fails without warning, and every rule you add makes the interactions harder to maintain.',
    tags: ['commercial', 'boom'],
  },
  {
    id: 'knowledge-engineering',
    family: 'symbolic',
    name: 'Common-Sense Knowledge Bases',
    short: 'Hand-encode everything a person knows',
    earliest: 1984,
    prereqs: ['expert-systems'],
    cost: 90,
    computeNeed: 8,
    capability: 6,
    understanding: 10,
    hype: 30,
    brittleness: 0.78,
    anchor: { year: 1984, who: 'Douglas Lenat — Cyc' },
    codex:
      'Lenat’s diagnosis was that expert systems were brittle because they lacked the ordinary background knowledge every human has, so he set out to enter it by hand: millions of assertions, decades of work. It is the most sustained bet ever placed on the symbolic hypothesis. Whether it was too small a bet or the wrong bet is still argued.',
    tags: ['long-shot'],
  },
  {
    id: 'cognitive-architecture',
    family: 'symbolic',
    name: 'Unified Cognitive Architectures',
    short: 'One machine, all of cognition',
    earliest: 1983,
    prereqs: ['gps', 'expert-systems'],
    cost: 70,
    computeNeed: 8,
    capability: 5,
    understanding: 14,
    hype: 22,
    brittleness: 0.55,
    anchor: { year: 1983, who: 'Newell, Laird & Rosenbloom — Soar; Anderson — ACT*' },
    codex:
      'Newell’s complaint was that the field produced a new theory for every experiment and never assembled them. A cognitive architecture is a fixed set of mechanisms — production memory, chunking, a decision cycle — proposed as the substrate of *all* thinking, and then tested against human reaction times. Its ambition and its obscurity have the same cause: it refused to specialise.',
  },
  {
    id: 'case-based',
    family: 'symbolic',
    name: 'Case-Based Reasoning',
    short: 'Remember; adapt; do not re-derive',
    earliest: 1982,
    prereqs: ['expert-systems'],
    cost: 48,
    computeNeed: 7.5,
    capability: 6,
    understanding: 7,
    hype: 8,
    brittleness: 0.3,
    anchor: { year: 1982, who: 'Roger Schank — Dynamic Memory' },
    codex:
      'Experts often do not reason from first principles; they recall a similar case and adjust. Schank made memory rather than logic the centre of the architecture, which put retrieval, indexing and similarity — later the whole apparatus of nearest-neighbour methods — at the heart of a supposedly symbolic system. Quietly, this is the bridge the field kept refusing to walk across.',
  },
  {
    id: 'ilp',
    family: 'symbolic',
    name: 'Inductive Logic Programming',
    short: 'Learn the rules instead of writing them',
    earliest: 1991,
    prereqs: ['logic-programming'],
    cost: 62,
    computeNeed: 9,
    capability: 6,
    understanding: 13,
    hype: 7,
    brittleness: 0.2,
    anchor: { year: 1991, who: 'Stephen Muggleton' },
    codex:
      'The symbolic school’s own answer to learning: search the space of logic programs for one that entails your positive examples and none of your negatives. What it produces is a readable theory rather than a weight matrix, which makes it the most interpretable form of machine learning ever built — and among the hardest to scale.',
    tags: ['interpretable'],
  },
  {
    id: 'description-logics',
    family: 'symbolic',
    name: 'Description Logics & Ontologies',
    short: 'Decidable fragments, machine-readable meaning',
    earliest: 1991,
    prereqs: ['resolution', 'knowledge-engineering'],
    cost: 58,
    computeNeed: 9,
    capability: 7,
    understanding: 10,
    hype: 16,
    brittleness: 0.55,
    anchor: { year: 2001, who: 'Berners-Lee, Hendler & Lassila — the Semantic Web' },
    codex:
      'If full first-order logic is intractable, carve out a fragment that is expressive enough to describe a domain and still decidable. Ontologies built this way run quietly under biomedical databases and industrial catalogues to this day. The grander vision — a web whose meaning machines could read — foundered less on the logic than on the fact that nobody wants to annotate anything.',
  },
  {
    id: 'program-synthesis',
    family: 'symbolic',
    name: 'Program Synthesis',
    short: 'From specification to code, provably',
    earliest: 1980,
    prereqs: ['resolution', 'heuristic-search'],
    cost: 78,
    computeNeed: 10,
    capability: 8,
    understanding: 12,
    hype: 10,
    brittleness: 0.3,
    anchor: { year: 1980, who: 'Manna & Waldinger — deductive synthesis' },
    codex:
      'Derive a program from a specification the way you derive a proof from axioms, so that correctness is a by-product of the construction rather than something you test for afterwards. For decades it worked only on programs small enough to write by hand. Its value is that it is one of the very few routes to a system that can say *why* its output is right.',
    tags: ['verification'],
  },
  /*
   * The five nodes below close a gap that was indefensible: this school had nothing at all
   * after 1991, alone among the eight, while the game elsewhere argues that the quiet schools
   * kept shipping. Symbolic AI did not stop having ideas when the funding moved — it stopped
   * having *press*, and went and solved the problems underneath everybody else's stack.
   */
  {
    id: 'modern-sat',
    family: 'symbolic',
    name: 'Industrial SAT Solving',
    short: 'Learn a clause from every failure',
    earliest: 2001,
    prereqs: ['resolution'],
    cost: 62,
    computeNeed: 12,
    capability: 13,
    understanding: 12,
    hype: 6,
    brittleness: 0.1,
    anchor: { year: 2001, who: 'Moskewicz et al. — Chaff; the CDCL solvers' },
    codex:
      'Satisfiability is the canonical hard problem, and conflict-driven clause learning made it routine anyway: when the search hits a contradiction, work out which decisions caused it, record that as a new clause, and jump back past all of them. Instances with millions of variables became a Tuesday. Almost nobody files this under AI, which is a good indication of how the field decides what counts — it is heuristic search, invented by the same people, working better than anyone in 1965 dared claim.',
    tags: ['durable'],
  },
  {
    id: 'smt',
    family: 'symbolic',
    name: 'Satisfiability Modulo Theories',
    short: 'A solver that understands arithmetic',
    earliest: 2008,
    prereqs: ['modern-sat'],
    cost: 66,
    computeNeed: 13,
    capability: 14,
    understanding: 13,
    hype: 7,
    brittleness: 0.1,
    anchor: { year: 2008, who: 'de Moura & Bjørner — Z3' },
    codex:
      'Bolt decision procedures for arithmetic, arrays and bit-vectors onto a clause-learning core and the solver stops reasoning about anonymous booleans and starts reasoning about programs. It is the engine inside compilers, static analysers, symbolic execution and most industrial verification, and it is the clearest surviving case of the symbolic programme delivering exactly what it promised in 1958 — a machine that manipulates symbols according to rules, at a scale that makes it useful.',
    tags: ['durable'],
  },
  {
    id: 'proof-assistants',
    family: 'symbolic',
    name: 'Machine-Checked Mathematics',
    short: 'A proof a machine agrees with',
    earliest: 2005,
    prereqs: ['resolution'],
    cost: 70,
    computeNeed: 12,
    capability: 8,
    understanding: 22,
    hype: 8,
    brittleness: 0.08,
    anchor: { year: 2005, who: 'Gonthier — the four colour theorem in Coq; Hales — Flyspeck, 2014' },
    codex:
      'The four colour theorem had been proved in 1976 by a computation nobody could check by hand, which many mathematicians refused to accept as a proof at all. Gonthier settled it by making the whole argument machine-checkable, and Hales did the same for Kepler after a referee panel gave up. What began as a way to answer sceptics became a working tool: a library of formalised mathematics that thousands of people build on and no one person has read.',
    tags: ['theory', 'durable'],
  },
  {
    id: 'verified-systems',
    family: 'symbolic',
    name: 'Verified Systems Engineering',
    short: 'Proved, not tested',
    earliest: 2009,
    prereqs: ['smt', 'proof-assistants'],
    cost: 80,
    computeNeed: 14,
    capability: 15,
    understanding: 20,
    hype: 7,
    brittleness: 0.06,
    anchor: { year: 2009, who: 'Klein et al. — seL4; Leroy — CompCert' },
    codex:
      'An operating system kernel and a C compiler, each proved to do what its specification says, machine-checked end to end. Two decades earlier both were the standing examples of what formal methods could never scale to. They ship in phones, vehicles and medical devices, in the layer that is not permitted to fail, and the proofs are artefacts you can rerun. The cost is that the specification becomes the hard part — you get exactly what you asked for, and finding out what you asked for is now the whole job.',
    tags: ['governance', 'durable'],
  },
  {
    id: 'knowledge-graphs',
    family: 'symbolic',
    name: 'Web-Scale Knowledge Graphs',
    short: 'Cyc, achieved by other means',
    earliest: 2012,
    prereqs: ['knowledge-engineering', 'description-logics'],
    cost: 72,
    computeNeed: 14,
    capability: 16,
    understanding: 12,
    hype: 14,
    brittleness: 0.2,
    anchor: { year: 2012, who: 'Wikidata and the industrial knowledge graphs' },
    codex:
      'Billions of typed assertions with a schema, curated partly by volunteers and partly by extraction, answering questions in front of hundreds of millions of people daily. This is the thing hand knowledge engineering spent thirty years failing to build at a tenth the size — achieved by giving up on completeness, on consistency, and on the idea that a single team could write it. The lesson the symbolic school paid most dearly for: the representation was never the bottleneck, the labour was.',
    tags: ['commercial'],
  },
  {
    id: 'automated-conjecture',
    family: 'symbolic',
    name: 'Automated Conjecture',
    short: 'Propose the theorem, not just the proof',
    earliest: 2038,
    prereqs: ['proof-assistants', 'program-synthesis'],
    familyPrereqs: { statistical: 40 },
    cost: 120,
    computeNeed: 24,
    capability: 22,
    understanding: 26,
    hype: 20,
    brittleness: 0.25,
    anchor: { year: 2038, who: '' },
    codex:
      'Proving a stated theorem was mechanised decades ago. Deciding which statement is worth proving was not, and it is the part working mathematicians describe as the actual job. A system that generates conjectures, ranks them by how much of the existing library they would reorganise, and discards the true-but-boring is doing taste — and taste was the last thing anybody expected to formalise. Lenat tried it in 1976 and the attempt collapsed under its own heuristics, which is why nobody tried again for sixty years.',
    tags: ['speculative'],
  },
];
