import type { Paradigm } from '../../engine/types';

export const SYMBOLIC: Paradigm[] = [
  {
    id: 'logic-theorist',
    family: 'symbolic',
    name: 'Heuristic Proof Search',
    short: 'A machine that proves theorems',
    earliest: 1955,
    prereqs: [],
    cost: 24,
    computeNeed: 4.5,
    capability: 2,
    understanding: 4,
    hype: 8,
    brittleness: 0.3,
    anchor: { year: 1956, who: 'Newell, Simon & Shaw — Logic Theorist' },
    codex:
      'The first program that did something everyone agreed was thinking: it proved theorems from Principia Mathematica, and found a proof of one that was shorter than Russell and Whitehead’s. Its real contribution was the idea of heuristic search — you cannot examine every branch, so you use rules of thumb to decide which branch is worth examining. Nearly all of symbolic AI is a variation on that sentence.',
    tags: ['founding'],
  },
  {
    id: 'lisp',
    family: 'symbolic',
    name: 'List Processing',
    short: 'A language where code is data',
    earliest: 1958,
    prereqs: ['logic-theorist'],
    cost: 28,
    computeNeed: 5,
    capability: 3,
    understanding: 6,
    hype: 4,
    brittleness: 0.1,
    anchor: { year: 1958, who: 'John McCarthy' },
    codex:
      'McCarthy wanted a notation for writing programs that reason about programs, and produced a language in which the two are the same kind of object. Recursion, garbage collection, the read-eval-print loop and the conditional expression all arrive together. For thirty years, if you were doing AI, you were almost certainly doing it in some dialect of this.',
    tags: ['tooling'],
  },
  {
    id: 'gps',
    family: 'symbolic',
    name: 'Means-Ends Analysis',
    short: 'Close the gap between here and the goal',
    earliest: 1959,
    prereqs: ['logic-theorist'],
    cost: 32,
    computeNeed: 5.2,
    capability: 3,
    understanding: 5,
    hype: 12,
    brittleness: 0.5,
    anchor: { year: 1959, who: 'Newell & Simon — General Problem Solver' },
    codex:
      'Measure the difference between the current state and the goal, find an operator that reduces that difference, apply it, repeat. Its authors believed it modelled how people actually solve problems, and collected think-aloud protocols to check. The word "General" in the name turned out to be the expensive part: it was general over toy problems and helpless outside them.',
  },
  {
    id: 'heuristic-search',
    family: 'symbolic',
    name: 'Informed Search',
    short: 'Admissible heuristics, optimal paths',
    earliest: 1966,
    prereqs: ['gps'],
    cost: 34,
    computeNeed: 6,
    capability: 5,
    understanding: 7,
    hype: 3,
    brittleness: 0.05,
    anchor: { year: 1968, who: 'Hart, Nilsson & Raphael — A*' },
    codex:
      'The proof that if your heuristic never overestimates the remaining distance, best-first search finds the optimal path and expands no more nodes than necessary. Unglamorous, entirely correct, and still running inside every route planner and game engine on Earth. Symbolic AI’s most durable export.',
    tags: ['durable'],
  },
  {
    id: 'resolution',
    family: 'symbolic',
    name: 'Resolution Theorem Proving',
    short: 'One inference rule, mechanically complete',
    earliest: 1965,
    prereqs: ['lisp'],
    cost: 36,
    computeNeed: 6,
    capability: 3,
    understanding: 9,
    hype: 6,
    brittleness: 0.2,
    anchor: { year: 1965, who: 'J. Alan Robinson' },
    codex:
      'Robinson reduced first-order logical inference to a single rule applied to clauses, with unification doing the pattern matching. Complete, in the sense that anything entailed will eventually be derived — where "eventually" is doing an enormous amount of work. The gap between completeness and tractability is the central tragedy of the logical approach.',
  },
  {
    id: 'logic-programming',
    family: 'symbolic',
    name: 'Logic Programming',
    short: 'State the problem; the prover is the program',
    earliest: 1972,
    prereqs: ['resolution'],
    cost: 42,
    computeNeed: 6.8,
    capability: 6,
    understanding: 8,
    hype: 14,
    brittleness: 0.4,
    anchor: { year: 1972, who: 'Colmerauer & Kowalski — Prolog' },
    codex:
      'If resolution can derive anything entailed by your axioms, then writing the axioms *is* programming. Prolog made that practical by fixing a search order, which meant the declarative dream came with a very procedural set of things you had to know about clause ordering. Europe and later Japan bet heavily on it.',
  },
  {
    id: 'expert-systems',
    family: 'symbolic',
    name: 'Expert Systems',
    short: 'Bottle a specialist in a thousand rules',
    earliest: 1968,
    prereqs: ['lisp'],
    cost: 46,
    computeNeed: 6.5,
    capability: 9,
    understanding: 4,
    hype: 34,
    brittleness: 0.85,
    anchor: { year: 1972, who: 'Feigenbaum, Buchanan & Shortliffe — DENDRAL, MYCIN' },
    codex:
      'The strategic retreat that worked: stop trying to build general intelligence, interview a domain expert, and encode their rules. MYCIN diagnosed blood infections about as well as the faculty. The catch is that such a system has no idea where its own edges are — one step outside its rules it fails without warning, and every rule you add makes the interactions harder to maintain.',
    tags: ['commercial', 'boom'],
  },
  {
    id: 'knowledge-engineering',
    family: 'symbolic',
    name: 'Common-Sense Knowledge Bases',
    short: 'Hand-encode everything a person knows',
    earliest: 1984,
    prereqs: ['expert-systems'],
    cost: 90,
    computeNeed: 8,
    capability: 6,
    understanding: 10,
    hype: 22,
    brittleness: 0.7,
    anchor: { year: 1984, who: 'Douglas Lenat — Cyc' },
    codex:
      'Lenat’s diagnosis was that expert systems were brittle because they lacked the ordinary background knowledge every human has, so he set out to enter it by hand: millions of assertions, decades of work. It is the most sustained bet ever placed on the symbolic hypothesis. Whether it was too small a bet or the wrong bet is still argued.',
    tags: ['long-shot'],
  },
  {
    id: 'cognitive-architecture',
    family: 'symbolic',
    name: 'Unified Cognitive Architectures',
    short: 'One machine, all of cognition',
    earliest: 1983,
    prereqs: ['gps', 'expert-systems'],
    cost: 70,
    computeNeed: 8,
    capability: 5,
    understanding: 14,
    hype: 12,
    brittleness: 0.3,
    anchor: { year: 1983, who: 'Newell, Laird & Rosenbloom — Soar; Anderson — ACT*' },
    codex:
      'Newell’s complaint was that the field produced a new theory for every experiment and never assembled them. A cognitive architecture is a fixed set of mechanisms — production memory, chunking, a decision cycle — proposed as the substrate of *all* thinking, and then tested against human reaction times. Its ambition and its obscurity have the same cause: it refused to specialise.',
  },
  {
    id: 'case-based',
    family: 'symbolic',
    name: 'Case-Based Reasoning',
    short: 'Remember; adapt; do not re-derive',
    earliest: 1982,
    prereqs: ['expert-systems'],
    cost: 48,
    computeNeed: 7.5,
    capability: 6,
    understanding: 7,
    hype: 8,
    brittleness: 0.3,
    anchor: { year: 1982, who: 'Roger Schank — Dynamic Memory' },
    codex:
      'Experts often do not reason from first principles; they recall a similar case and adjust. Schank made memory rather than logic the centre of the architecture, which put retrieval, indexing and similarity — later the whole apparatus of nearest-neighbour methods — at the heart of a supposedly symbolic system. Quietly, this is the bridge the field kept refusing to walk across.',
  },
  {
    id: 'ilp',
    family: 'symbolic',
    name: 'Inductive Logic Programming',
    short: 'Learn the rules instead of writing them',
    earliest: 1991,
    prereqs: ['logic-programming'],
    cost: 62,
    computeNeed: 9,
    capability: 6,
    understanding: 13,
    hype: 7,
    brittleness: 0.2,
    anchor: { year: 1991, who: 'Stephen Muggleton' },
    codex:
      'The symbolic school’s own answer to learning: search the space of logic programs for one that entails your positive examples and none of your negatives. What it produces is a readable theory rather than a weight matrix, which makes it the most interpretable form of machine learning ever built — and among the hardest to scale.',
    tags: ['interpretable'],
  },
  {
    id: 'description-logics',
    family: 'symbolic',
    name: 'Description Logics & Ontologies',
    short: 'Decidable fragments, machine-readable meaning',
    earliest: 1991,
    prereqs: ['resolution', 'knowledge-engineering'],
    cost: 58,
    computeNeed: 9,
    capability: 7,
    understanding: 10,
    hype: 16,
    brittleness: 0.55,
    anchor: { year: 2001, who: 'Berners-Lee, Hendler & Lassila — the Semantic Web' },
    codex:
      'If full first-order logic is intractable, carve out a fragment that is expressive enough to describe a domain and still decidable. Ontologies built this way run quietly under biomedical databases and industrial catalogues to this day. The grander vision — a web whose meaning machines could read — foundered less on the logic than on the fact that nobody wants to annotate anything.',
  },
  {
    id: 'program-synthesis',
    family: 'symbolic',
    name: 'Program Synthesis',
    short: 'From specification to code, provably',
    earliest: 1980,
    prereqs: ['resolution', 'heuristic-search'],
    cost: 78,
    computeNeed: 10,
    capability: 8,
    understanding: 12,
    hype: 10,
    brittleness: 0.3,
    anchor: { year: 1980, who: 'Manna & Waldinger — deductive synthesis' },
    codex:
      'Derive a program from a specification the way you derive a proof from axioms, so that correctness is a by-product of the construction rather than something you test for afterwards. For decades it worked only on programs small enough to write by hand. Its value is that it is one of the very few routes to a system that can say *why* its output is right.',
    tags: ['verification'],
  },
];
