import type { Character, FamilyId } from '../engine/types';

/**
 * DEPICTION RULES — enforced by tools/lint-content.ts and by review.
 *
 *  - `kind: 'historical'` characters are real people. They appear only in documented
 *    professional roles, and every line they speak is a paraphrase of a position they took in
 *    print. `sources` is mandatory and lists where that position comes from.
 *  - No invented private life, no invented misconduct, no dialogue that contradicts a person's
 *    known views, and nothing said by a real person about events they did not live to see.
 *  - `span` is the window in which the character may appear on screen. For historical figures
 *    it is bounded by their documented period of activity in this field.
 *  - Everyone appearing after 2026 is `kind: 'fictional'`. The game's speculative acts put no
 *    words in any living person's mouth.
 *  - Portraits are deliberately abstract geometric figures. They are not likenesses.
 */
export const CHARACTERS: Character[] = [
  // ---------------------------------------------------------------- Act I
  {
    id: 'turing',
    name: 'Alan Turing',
    kind: 'historical',
    family: null,
    span: [1950, 1954],
    portraitSeed: 1912,
    look: { era: 1950, build: 'slim', hair: 'short', glasses: false, accent: '#c8b08a' },
    bio: 'Mathematician and computer scientist. In 1950 he proposed replacing the question "can machines think?" with an imitation game, and sketched the idea of a child machine that would be educated rather than programmed.',
    sources: ['Computing Machinery and Intelligence (Mind, 1950)', 'Intelligent Machinery (NPL report, 1948)'],
  },
  {
    id: 'wiener',
    name: 'Norbert Wiener',
    kind: 'historical',
    family: 'cybernetic',
    span: [1950, 1964],
    portraitSeed: 1894,
    look: { era: 1950, build: 'round', hair: 'short', facial: 'beard', glasses: true, accent: '#b5646b' },
    bio: 'Founder of cybernetics. Argued that feedback explains purposive behaviour in animals and machines alike, and warned publicly and early about the economic consequences of automation.',
    sources: ['Cybernetics (1948)', 'The Human Use of Human Beings (1950)'],
  },
  {
    id: 'ashby',
    name: 'W. Ross Ashby',
    kind: 'historical',
    family: 'cybernetic',
    span: [1950, 1972],
    portraitSeed: 1903,
    look: { era: 1950, build: 'slim', hair: 'short', glasses: true, accent: '#b5646b' },
    bio: 'Psychiatrist and cybernetician. Built the homeostat, a machine that returned itself to stability after arbitrary disturbance, and formulated the Law of Requisite Variety.',
    sources: ['Design for a Brain (1952)', 'An Introduction to Cybernetics (1956)'],
  },
  {
    id: 'mcculloch',
    name: 'Warren McCulloch',
    kind: 'historical',
    family: 'connectionist',
    span: [1950, 1969],
    portraitSeed: 1898,
    look: { era: 1950, build: 'broad', hair: 'wild', facial: 'beard', accent: '#6fb0c8' },
    bio: 'Neurophysiologist. With Walter Pitts, showed that networks of idealised threshold neurons can compute any logical proposition — the founding formal result of the connectionist tradition.',
    sources: ['A Logical Calculus of the Ideas Immanent in Nervous Activity (1943)'],
  },
  {
    id: 'shannon',
    name: 'Claude Shannon',
    kind: 'historical',
    family: 'statistical',
    span: [1950, 1966],
    portraitSeed: 1916,
    look: { era: 1950, build: 'slim', hair: 'short', accent: '#9a7fc8' },
    bio: 'Founder of information theory. In 1951 he measured the entropy of written English by having a subject guess a novel one letter at a time, defining the next-symbol prediction problem that every language model since has been scored on. Also built a maze-solving mechanical mouse and one of the first chess programs, and was a co-organiser of the 1956 Dartmouth study.',
    sources: [
      'A Mathematical Theory of Communication (1948)',
      'Prediction and Entropy of Printed English (Bell System Technical Journal, 1951)',
      'Programming a Computer for Playing Chess (1950)',
    ],
  },
  {
    id: 'mccarthy',
    name: 'John McCarthy',
    kind: 'historical',
    family: 'symbolic',
    span: [1955, 2011],
    portraitSeed: 1927,
    look: { era: 1955, build: 'slim', hair: 'wild', facial: 'beard', glasses: true, accent: '#d8a24a' },
    bio: 'Coined the term "artificial intelligence" in the 1955 Dartmouth proposal, created LISP, and argued throughout his career that intelligence requires an explicit formal representation of common-sense facts.',
    sources: [
      'A Proposal for the Dartmouth Summer Research Project (1955)',
      'Recursive Functions of Symbolic Expressions (1960)',
      'Programs with Common Sense (1959)',
    ],
  },
  {
    id: 'minsky',
    name: 'Marvin Minsky',
    kind: 'historical',
    family: 'connectionist',
    /*
     * The clearest case in the cast of somebody changing their mind in public, twice, and
     * meaning it every time. Built a forty-synapse reinforcement learning machine as a graduate
     * student, spent two decades on symbolic AI and co-wrote the book that bounded what a
     * one-layer network could compute, then proposed mind as a society of mindless agents.
     */
    affiliations: [
      { from: 1951, family: 'connectionist' },
      { from: 1959, family: 'symbolic' },
      { from: 1986, family: 'collective' },
    ],
    span: [1955, 2016],
    portraitSeed: 1927.5,
    look: { era: 1955, build: 'broad', hair: 'bald', glasses: true, accent: '#d8a24a' },
    bio: 'Co-founder of the MIT AI Laboratory, and the cast\u2019s clearest case of somebody changing schools in public. Built SNARC, a forty-synapse reinforcement learning machine, with Dean Edmonds in 1951; spent the following two decades on symbolic AI and co-authored the formal analysis bounding what single-layer perceptrons can compute; then in 1986 proposed mind as a society of simple mindless agents with no central controller.',
    sources: [
      'SNARC, with Dean Edmonds (1951)',
      'Steps Toward Artificial Intelligence (1961)',
      'Perceptrons (with Papert, 1969)',
      'The Society of Mind (1986)',
    ],
  },
  {
    id: 'rosenblatt',
    name: 'Frank Rosenblatt',
    kind: 'historical',
    family: 'connectionist',
    span: [1957, 1971],
    portraitSeed: 1928,
    look: { era: 1957, build: 'slim', hair: 'short', glasses: true, accent: '#6fb0c8' },
    bio: 'Psychologist at Cornell. Devised the perceptron and proved its convergence theorem, built the Mark I as physical hardware, and held that a brain-like machine must be understood statistically rather than as a program.',
    sources: ['The Perceptron: A Probabilistic Model (Psych. Review, 1958)', 'Principles of Neurodynamics (1962)'],
  },
  {
    id: 'newell',
    name: 'Allen Newell',
    kind: 'historical',
    family: 'symbolic',
    span: [1955, 1992],
    portraitSeed: 1927.2,
    look: { era: 1955, build: 'slim', hair: 'short', accent: '#d8a24a' },
    bio: 'With Herbert Simon, built the Logic Theorist and the General Problem Solver, formulated the physical symbol system hypothesis, and spent his last years arguing the field needed unified theories rather than more demonstrations.',
    sources: ['The Logic Theory Machine (1956)', 'Computer Science as Empirical Inquiry (1976)', 'Unified Theories of Cognition (1990)'],
  },
  {
    id: 'simon',
    name: 'Herbert Simon',
    kind: 'historical',
    family: 'symbolic',
    span: [1955, 2001],
    portraitSeed: 1916.3,
    look: { era: 1955, build: 'round', hair: 'short', glasses: true, accent: '#d8a24a' },
    bio: 'Political scientist, economist and cognitive scientist. Argued that real decision-makers satisfice rather than optimise, and that heuristic search in a problem space is the mechanism of human problem solving.',
    sources: ['Administrative Behavior (1947)', 'Human Problem Solving (with Newell, 1972)', 'The Sciences of the Artificial (1969)'],
  },
  {
    id: 'samuel',
    name: 'Arthur Samuel',
    kind: 'historical',
    family: 'cybernetic',
    span: [1952, 1990],
    portraitSeed: 1901,
    look: { era: 1952, build: 'slim', hair: 'short', glasses: true, accent: '#c86f8a' },
    bio: 'IBM engineer whose checkers program improved its own evaluation function from experience and eventually beat him. He gave the field the phrase "machine learning".',
    sources: ['Some Studies in Machine Learning Using the Game of Checkers (IBM Journal, 1959)'],
  },
  {
    id: 'selfridge',
    name: 'Oliver Selfridge',
    kind: 'historical',
    family: 'connectionist',
    span: [1955, 1990],
    portraitSeed: 1926,
    look: { era: 1955, build: 'slim', hair: 'short', accent: '#6fb0c8' },
    bio: 'Proposed Pandemonium, an architecture of competing feature detectors shouting at increasing volume — an early parallel, learning alternative to sequential rule-following.',
    sources: ['Pandemonium: A Paradigm for Learning (1959)'],
  },
  {
    id: 'solomonoff',
    name: 'Ray Solomonoff',
    kind: 'historical',
    family: 'statistical',
    span: [1956, 2009],
    portraitSeed: 1926.4,
    look: { era: 1956, build: 'slim', hair: 'short', glasses: true, accent: '#9a7fc8' },
    bio: 'Attended the Dartmouth workshop and spent the following decades on algorithmic probability: a formal prior in which the shortest computable explanation of the data is the most likely one.',
    sources: ['A Formal Theory of Inductive Inference (Information and Control, 1964)'],
  },
  {
    id: 'widrow',
    name: 'Bernard Widrow',
    kind: 'historical',
    family: 'connectionist',
    span: [1959, 2005],
    portraitSeed: 1929,
    look: { era: 1959, build: 'slim', hair: 'short', glasses: true, accent: '#6fb0c8' },
    bio: 'With Marcian Hoff, devised the least-mean-squares learning rule and built adaptive linear elements in hardware. The same algorithm became adaptive filtering in telecommunications.',
    sources: ['Adaptive Switching Circuits (1960)', 'Adaptive Signal Processing (1985)'],
  },

  // ---------------------------------------------------------------- Act II
  {
    id: 'papert',
    name: 'Seymour Papert',
    kind: 'historical',
    family: 'symbolic',
    span: [1963, 2000],
    portraitSeed: 1928.6,
    look: { era: 1963, build: 'slim', hair: 'short', glasses: true, accent: '#d8a24a' },
    bio: 'Mathematician and educator who worked with Piaget before joining MIT. Co-authored the formal study of perceptron limitations, and later built Logo around the idea that children learn by constructing things.',
    sources: ['Perceptrons (with Minsky, 1969)', 'Mindstorms (1980)'],
  },
  {
    id: 'holland',
    name: 'John Holland',
    kind: 'historical',
    family: 'evolutionary',
    span: [1962, 2015],
    portraitSeed: 1929.7,
    look: { era: 1962, build: 'slim', hair: 'short', glasses: true, accent: '#7fc86f' },
    bio: 'Founded the study of genetic algorithms and complex adaptive systems, arguing that a population searching in parallel with crossover explores far more of a space than its size suggests.',
    sources: ['Adaptation in Natural and Artificial Systems (1975)', 'Hidden Order (1995)'],
  },
  {
    id: 'zadeh',
    name: 'Lotfi Zadeh',
    kind: 'historical',
    family: 'bridge',
    span: [1965, 2017],
    portraitSeed: 1921,
    look: { era: 1965, build: 'slim', hair: 'short', facial: 'moustache', glasses: true, accent: '#c07fd8' },
    bio: 'Control theorist at Berkeley. Introduced fuzzy sets, holding that as complexity rises, precision and significance become mutually exclusive.',
    sources: ['Fuzzy Sets (Information and Control, 1965)', 'Outline of a New Approach to the Analysis of Complex Systems (1973)'],
  },
  {
    id: 'rechenberg',
    name: 'Ingo Rechenberg',
    kind: 'historical',
    family: 'evolutionary',
    span: [1964, 2010],
    portraitSeed: 1934,
    look: { era: 1964, build: 'broad', hair: 'short', accent: '#7fc86f' },
    bio: 'Aerospace engineer in Berlin who optimised physical shapes in a wind tunnel by random mutation and selection, founding evolution strategies before computers were fast enough to need them.',
    sources: ['Evolutionsstrategie (1973)'],
  },
  {
    id: 'dreyfus',
    name: 'Hubert Dreyfus',
    kind: 'historical',
    family: null,
    span: [1965, 2010],
    portraitSeed: 1929.9,
    look: { era: 1965, build: 'slim', hair: 'short', glasses: true, accent: '#8a8a8a' },
    bio: 'Philosopher at Berkeley and the field\'s most persistent critic. Argued from phenomenology that human expertise is embodied, situated know-how which cannot be captured as explicit rules.',
    sources: ['Alchemy and Artificial Intelligence (RAND, 1965)', 'What Computers Can\'t Do (1972)'],
  },
  {
    id: 'weizenbaum',
    name: 'Joseph Weizenbaum',
    kind: 'historical',
    family: null,
    span: [1966, 2008],
    portraitSeed: 1923,
    look: { era: 1966, build: 'slim', hair: 'short', glasses: true, accent: '#8a8a8a' },
    bio: 'Wrote ELIZA, was disturbed by how readily people confided in it, and spent the rest of his career distinguishing what computers can be made to do from what they ought to be asked to do.',
    sources: ['ELIZA (CACM, 1966)', 'Computer Power and Human Reason (1976)'],
  },
  {
    id: 'lighthill',
    name: 'Sir James Lighthill',
    kind: 'historical',
    family: null,
    span: [1972, 1975],
    portraitSeed: 1924,
    look: { era: 1972, build: 'round', hair: 'short', glasses: true, accent: '#8a8a8a' },
    bio: 'Applied mathematician commissioned by the British Science Research Council to review AI. His 1973 report found that results had not met claims, and singled out the combinatorial explosion as the reason.',
    sources: ['Artificial Intelligence: A General Survey (SRC, 1973)'],
  },
  {
    id: 'feigenbaum',
    name: 'Edward Feigenbaum',
    kind: 'historical',
    family: 'symbolic',
    span: [1965, 2010],
    portraitSeed: 1936,
    look: { era: 1965, build: 'slim', hair: 'short', glasses: true, accent: '#d8a24a' },
    bio: 'Led DENDRAL and argued that power comes from domain knowledge rather than general reasoning method — the founding claim of knowledge engineering and the expert systems industry.',
    sources: ['The Art of Artificial Intelligence (IJCAI, 1977)', 'The Fifth Generation (1983)'],
  },
  {
    id: 'kowalski',
    name: 'Robert Kowalski',
    kind: 'historical',
    family: 'symbolic',
    span: [1970, 2010],
    portraitSeed: 1941,
    look: { era: 1970, build: 'slim', hair: 'short', glasses: true, accent: '#d8a24a' },
    bio: 'Established the procedural interpretation of Horn clauses that made logic programming practical, summarised as: algorithm equals logic plus control.',
    sources: ['Predicate Logic as Programming Language (1974)', 'Algorithm = Logic + Control (CACM, 1979)'],
  },
  {
    id: 'vapnik',
    name: 'Vladimir Vapnik',
    kind: 'historical',
    family: 'statistical',
    span: [1971, 2020],
    portraitSeed: 1936.5,
    look: { era: 1971, build: 'broad', hair: 'short', facial: 'beard', glasses: true, accent: '#9a7fc8' },
    bio: 'With Alexey Chervonenkis, established the theory bounding generalisation error by the capacity of a hypothesis class; later co-developed support vector machines.',
    sources: ['On the Uniform Convergence of Relative Frequencies (1971)', 'Support-Vector Networks (with Cortes, 1995)'],
  },

  // ---------------------------------------------------------------- Act III
  {
    id: 'lenat',
    name: 'Douglas Lenat',
    kind: 'historical',
    family: 'symbolic',
    span: [1977, 2020],
    portraitSeed: 1950,
    look: { era: 1977, build: 'slim', hair: 'short', facial: 'beard', glasses: true, accent: '#d8a24a' },
    bio: 'After building programs that discovered mathematical concepts, concluded that the missing ingredient was ordinary common-sense knowledge, and began entering it by hand as the Cyc project.',
    sources: ['AM: Discovery in Mathematics as Heuristic Search (1976)', 'Building Large Knowledge-Based Systems (1989)'],
  },
  {
    id: 'hopfield',
    name: 'John Hopfield',
    kind: 'historical',
    family: 'connectionist',
    span: [1982, 2020],
    portraitSeed: 1933,
    look: { era: 1982, build: 'slim', hair: 'short', glasses: true, accent: '#6fb0c8' },
    bio: 'Physicist who showed that a symmetric recurrent network descends an energy function, so its stable states behave as content-addressable memories — importing statistical physics into neural network research.',
    sources: ['Neural Networks and Physical Systems with Emergent Collective Computational Abilities (PNAS, 1982)'],
  },
  {
    id: 'hinton',
    name: 'Geoffrey Hinton',
    kind: 'historical',
    family: 'connectionist',
    span: [1982, 2026],
    portraitSeed: 1947,
    look: { era: 1982, build: 'slim', hair: 'short', glasses: true, accent: '#6fb0c8' },
    bio: 'Co-developed the Boltzmann machine and, with Rumelhart and Williams, brought backpropagation to the field; later showed layer-wise pre-training made deep networks trainable.',
    sources: [
      'Learning Representations by Back-propagating Errors (Nature, 1986)',
      'A Learning Algorithm for Boltzmann Machines (1985)',
      'A Fast Learning Algorithm for Deep Belief Nets (2006)',
    ],
  },
  {
    id: 'rumelhart',
    name: 'David Rumelhart',
    kind: 'historical',
    family: 'connectionist',
    span: [1982, 1998],
    portraitSeed: 1942,
    look: { era: 1982, build: 'slim', hair: 'short', accent: '#6fb0c8' },
    bio: 'Cognitive psychologist and co-editor of the Parallel Distributed Processing volumes, which argued that cognition is better modelled by distributed representations than by explicit rules.',
    sources: ['Parallel Distributed Processing (with McClelland, 1986)'],
  },
  {
    id: 'pearl',
    name: 'Judea Pearl',
    kind: 'historical',
    family: 'symbolic',
    // Came to probability through heuristic search, not the other way round.
    affiliations: [
      { from: 1982, family: 'symbolic' },
      { from: 1988, family: 'statistical' },
    ],
    span: [1982, 2026],
    portraitSeed: 1936.8,
    look: { era: 1982, build: 'slim', hair: 'short', glasses: true, accent: '#9a7fc8' },
    bio: 'Worked first on heuristic search and game trees, then introduced Bayesian networks as a tractable representation of probabilistic knowledge, and finally developed the calculus of interventions and counterfactuals that distinguishes causation from correlation.',
    sources: [
      'Heuristics: Intelligent Search Strategies for Computer Problem Solving (1984)',
      'Probabilistic Reasoning in Intelligent Systems (1988)',
      'Causality (2000)',
    ],
  },
  {
    id: 'brooks',
    name: 'Rodney Brooks',
    kind: 'historical',
    family: 'cybernetic',
    span: [1985, 2026],
    portraitSeed: 1954,
    look: { era: 1985, build: 'broad', hair: 'short', facial: 'beard', accent: '#c86f8a' },
    bio: 'Built robots with layered reactive behaviours and no central world model, arguing that representation is often unnecessary and that the world serves as its own best model.',
    sources: ['A Robust Layered Control System for a Mobile Robot (1986)', 'Intelligence Without Representation (1991)', 'Elephants Don\'t Play Chess (1990)'],
  },
  {
    id: 'mead',
    name: 'Carver Mead',
    kind: 'historical',
    family: 'substrate',
    span: [1980, 2020],
    portraitSeed: 1934.2,
    look: { era: 1980, build: 'slim', hair: 'short', glasses: true, accent: '#6fc8b0' },
    bio: 'With Lynn Conway, made VLSI design teachable; then observed that transistors below threshold obey physics resembling ion channels, and founded neuromorphic engineering.',
    sources: ['Introduction to VLSI Systems (with Conway, 1980)', 'Analog VLSI and Neural Systems (1989)'],
  },
  {
    id: 'hillis',
    name: 'Danny Hillis',
    kind: 'historical',
    family: 'substrate',
    span: [1983, 2010],
    portraitSeed: 1956,
    look: { era: 1983, build: 'slim', hair: 'wild', glasses: true, accent: '#6fc8b0' },
    bio: 'Designed the Connection Machine, a massively parallel computer built on the premise that thinking machines should have many slow elements, and used it to coevolve sorting networks against their own test cases.',
    sources: ['The Connection Machine (1985)', 'Co-evolving Parasites Improve Simulated Evolution (1990)'],
  },
  {
    id: 'sutton',
    name: 'Richard Sutton',
    kind: 'historical',
    family: 'cybernetic',
    span: [1984, 2026],
    portraitSeed: 1957,
    look: { era: 1984, build: 'slim', hair: 'short', accent: '#c86f8a' },
    bio: 'Formalised temporal-difference learning, and has argued consistently that general methods which scale with computation ultimately outperform methods that encode human knowledge.',
    sources: ['Learning to Predict by the Methods of Temporal Differences (1988)', 'Reinforcement Learning: An Introduction (with Barto, 1998)', 'The Bitter Lesson (2019)'],
  },
  {
    id: 'lecun',
    name: 'Yann LeCun',
    kind: 'historical',
    family: 'connectionist',
    span: [1987, 2026],
    portraitSeed: 1960,
    look: { era: 1987, build: 'slim', hair: 'short', accent: '#6fb0c8' },
    bio: 'Applied backpropagation to convolutional networks for handwritten digit recognition, producing a system that read a large share of American cheques through the 1990s.',
    sources: ['Backpropagation Applied to Handwritten Zip Code Recognition (1989)', 'Gradient-Based Learning Applied to Document Recognition (1998)'],
  },
  {
    id: 'koza',
    name: 'John Koza',
    kind: 'historical',
    family: 'evolutionary',
    span: [1990, 2015],
    portraitSeed: 1943,
    look: { era: 1990, build: 'broad', hair: 'short', accent: '#7fc86f' },
    bio: 'Extended genetic algorithms to evolve executable programs represented as trees, and catalogued cases in which evolved designs matched or exceeded patented human inventions.',
    sources: ['Genetic Programming (1992)', 'Human-Competitive Results Produced by Genetic Programming (2010)'],
  },
  {
    id: 'kanerva',
    name: 'Pentti Kanerva',
    kind: 'historical',
    family: 'bridge',
    span: [1988, 2020],
    portraitSeed: 1939,
    look: { era: 1988, build: 'slim', hair: 'short', glasses: true, accent: '#c07fd8' },
    bio: 'Proposed sparse distributed memory, and later hyperdimensional computing: representing structured symbolic information as very long vectors that can be bound, superposed and decoded.',
    sources: ['Sparse Distributed Memory (1988)', 'Hyperdimensional Computing (Cognitive Computation, 2009)'],
  },
  {
    id: 'dorigo',
    name: 'Marco Dorigo',
    kind: 'historical',
    family: 'collective',
    span: [1991, 2026],
    portraitSeed: 1961,
    look: { era: 1991, build: 'slim', hair: 'short', accent: '#d89a4a' },
    bio: 'Turned the pheromone-trail behaviour of foraging ants into a general combinatorial optimisation method, and went on to found the field of swarm robotics.',
    sources: ['Optimization, Learning and Natural Algorithms (thesis, 1992)', 'Ant Colony Optimization (2004)'],
  },
  {
    id: 'schmidhuber',
    name: 'Jürgen Schmidhuber',
    kind: 'historical',
    family: 'connectionist',
    span: [1990, 2026],
    portraitSeed: 1963,
    look: { era: 1990, build: 'slim', hair: 'short', accent: '#6fb0c8' },
    bio: 'With Sepp Hochreiter, devised the long short-term memory cell that made recurrent networks trainable over long sequences; also an insistent historian of the field\'s priority claims.',
    sources: ['Long Short-Term Memory (Neural Computation, 1997)', 'Deep Learning in Neural Networks: An Overview (2015)'],
  },
  {
    id: 'thompson',
    name: 'Adrian Thompson',
    kind: 'historical',
    family: 'evolutionary',
    span: [1995, 2010],
    portraitSeed: 1969,
    look: { era: 1995, build: 'slim', hair: 'short', accent: '#7fc86f' },
    bio: 'Evolved a tone-discriminating circuit directly onto a field-programmable gate array and found it relied on analog side-effects of the silicon that no conventional design would use.',
    sources: ['An Evolved Circuit, Intrinsic in Silicon, Entwined with Physics (1996)'],
  },
  {
    id: 'hutchins',
    name: 'Edwin Hutchins',
    kind: 'historical',
    family: 'collective',
    span: [1995, 2015],
    portraitSeed: 1948,
    look: { era: 1995, build: 'slim', hair: 'short', facial: 'beard', accent: '#d89a4a' },
    bio: 'Cognitive anthropologist who analysed ship navigation as a computation distributed across people, instruments and procedures rather than performed by any individual mind.',
    sources: ['Cognition in the Wild (1995)'],
  },
  {
    id: 'moravec',
    name: 'Hans Moravec',
    kind: 'historical',
    family: 'cybernetic',
    span: [1985, 2010],
    portraitSeed: 1948.3,
    look: { era: 1985, build: 'slim', hair: 'short', glasses: true, accent: '#c86f8a' },
    bio: 'Roboticist who observed that the hardest problems for machines are the ones evolution solved longest ago: reasoning is comparatively easy, perception and locomotion are not.',
    sources: ['Mind Children (1988)'],
  },

  // ---------------------------------------------------------------- Acts IV-V
  {
    id: 'hutter',
    name: 'Marcus Hutter',
    kind: 'historical',
    family: 'statistical',
    span: [2000, 2026],
    portraitSeed: 1967,
    look: { era: 2000, build: 'slim', hair: 'short', glasses: true, accent: '#9a7fc8' },
    bio: 'Combined Solomonoff induction with sequential decision theory to specify a mathematically optimal — and uncomputable — general agent, giving the field a precise definition to argue with.',
    sources: ['Universal Artificial Intelligence (2005)'],
  },
  {
    id: 'stanley',
    name: 'Kenneth Stanley',
    kind: 'historical',
    family: 'evolutionary',
    span: [2002, 2026],
    portraitSeed: 1975,
    look: { era: 2002, build: 'slim', hair: 'short', accent: '#7fc86f' },
    bio: 'Developed NEAT, which evolves network topology as well as weights, and later argued that abandoning the objective in favour of novelty often reaches ambitious goals that direct search cannot.',
    sources: ['Evolving Neural Networks through Augmenting Topologies (2002)', 'Why Greatness Cannot Be Planned (with Lehman, 2015)'],
  },
  {
    id: 'friston',
    name: 'Karl Friston',
    kind: 'historical',
    family: 'cybernetic',
    span: [2005, 2026],
    portraitSeed: 1959,
    look: { era: 2005, build: 'slim', hair: 'short', accent: '#c86f8a' },
    bio: 'Neuroscientist who proposed that any system maintaining itself against disorder must act to minimise the surprise of its sensory states, unifying perception and action under one quantity.',
    sources: ['The Free-Energy Principle: A Unified Brain Theory? (Nature Reviews Neuroscience, 2010)'],
  },
  {
    id: 'bengio',
    name: 'Yoshua Bengio',
    kind: 'historical',
    family: 'connectionist',
    span: [1998, 2026],
    portraitSeed: 1964,
    look: { era: 1998, build: 'slim', hair: 'wild', accent: '#6fb0c8' },
    bio: 'Worked on neural language models and deep architectures through the years when few would; later became a prominent voice for caution about the systems that work produced.',
    sources: ['A Neural Probabilistic Language Model (2003)', 'Representation Learning: A Review (2013)'],
  },
  {
    id: 'li',
    name: 'Fei-Fei Li',
    kind: 'historical',
    family: 'connectionist',
    span: [2007, 2026],
    portraitSeed: 1976,
    look: { era: 2007, build: 'slim', hair: 'long', accent: '#6fb0c8' },
    bio: 'Argued that the bottleneck in machine vision was data rather than algorithms, and built a labelled image corpus of unprecedented scale — the benchmark on which the deep learning result of 2012 was won.',
    sources: ['ImageNet: A Large-Scale Hierarchical Image Database (2009)'],
  },

  // ---------------------------------------------------------------- Acts VI-VII (fictional)
  {
    id: 'halvorsen',
    name: 'Iris Halvorsen',
    kind: 'fictional',
    family: 'connectionist',
    span: [2026, 2046],
    portraitSeed: 4101,
    look: { era: 2026, build: 'slim', hair: 'tied', accent: '#6fb0c8' },
    bio: 'Research director at a frontier laboratory. Believes the curves have further to run and that the people who say otherwise have been saying so, wrongly, for fifteen years.',
  },
  {
    id: 'nkemelu',
    name: 'Adaeze Nkemelu',
    kind: 'fictional',
    family: 'bridge',
    span: [2026, 2050],
    portraitSeed: 4102,
    look: { era: 2026, build: 'slim', hair: 'short', glasses: true, accent: '#c07fd8' },
    bio: 'Director of an assurance institute, formerly a verification engineer for avionics. Asks the same question in every meeting: what would we have to know to sign this?',
  },
  {
    id: 'wieczorek',
    name: 'Tomasz Wieczorek',
    kind: 'fictional',
    family: 'substrate',
    span: [2024, 2050],
    portraitSeed: 4103,
    look: { era: 2028, build: 'broad', hair: 'short', facial: 'beard', accent: '#6fc8b0' },
    bio: 'Device physicist who thinks the entire software argument is downstream of a thermodynamics problem nobody in it has read about.',
  },
  {
    id: 'okonjo',
    name: 'Rafael Okonjo-Barros',
    kind: 'fictional',
    family: 'collective',
    // Invented, so the span is a choice rather than a record. Widened because a collective
    // century accretes early and its reckoning can come long before the 2030s.
    span: [2014, 2050],
    portraitSeed: 4104,
    look: { era: 2030, build: 'broad', hair: 'short', accent: '#d89a4a' },
    bio: 'Organiser for the distributed commons. Holds that the question was never which paradigm wins but who is permitted to run it.',
  },
  {
    id: 'sorensen',
    name: 'Meiling Sørensen',
    kind: 'fictional',
    family: 'cybernetic',
    // Widened for the same reason: eleven years of a machine in a house has to start somewhere,
    // and on this branch that can be the 2010s.
    span: [2018, 2050],
    portraitSeed: 4105,
    look: { era: 2030, build: 'slim', hair: 'tied', accent: '#c86f8a' },
    bio: 'Developmental roboticist. Raises her systems rather than training them, and is extremely tired of being asked how long it takes.',
  },
  {
    id: 'archivist',
    name: 'The Archivist',
    title: 'Archivist',
    kind: 'fictional',
    narrator: true,
    family: null,
    span: [1950, 2050],
    portraitSeed: 9001,
    look: { era: 1950, build: 'slim', hair: 'short', accent: '#8fa0b8' },
    bio: 'Keeps the record. Notices what the record leaves out. Has been doing this for longer than seems reasonable.',
  },
  {
    id: 'second',
    name: 'A Second Voice',
    title: '???',
    kind: 'fictional',
    narrator: true,
    family: null,
    span: [1950, 2050],
    portraitSeed: 9002,
    look: { era: 1950, build: 'slim', hair: 'short', accent: '#b8b8b8' },
    bio: 'Not listed in any directory. Speaks rarely, and only about the instrument you are looking through.',
  },
];

export const CHARACTER_BY_ID: Record<string, Character> = Object.fromEntries(
  CHARACTERS.map((c) => [c.id, c]),
);

export function character(id: string): Character {
  const c = CHARACTER_BY_ID[id];
  if (!c) throw new Error(`unknown character: ${id}`);
  return c;
}

/**
 * Which school this person belonged to in a given year.
 *
 * Allegiance is not a fixed property of a person. Minsky built a learning machine, then spent
 * twenty years arguing against learning machines, then proposed mind as a society of agents,
 * and every one of those was sincere. Backing him in 1955 is not backing the same programme as
 * backing him in 1990, and the board should say so.
 */
export function familyAt(c: Character, year: number): FamilyId | null {
  if (!c.affiliations?.length) return c.family;
  let current = c.family;
  for (const a of c.affiliations) {
    if (year >= a.from) current = a.family;
  }
  return current;
}

/** The arc in words, for the Codex: "connectionist → symbolic → collective". */
export function affiliationArc(c: Character): { from: number; family: FamilyId | null }[] {
  return c.affiliations ?? [];
}
